//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_CAT.CAT_Catalogue")]
    public partial class CAT_Catalogue : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fPublisher;
        [Size(50)]
        public string Publisher
        {
            get { return fPublisher; }
            set { SetPropertyValue<string>("Publisher", ref fPublisher, value); }
        }
        string fRevision;
        [Size(50)]
        public string Revision
        {
            get { return fRevision; }
            set { SetPropertyValue<string>("Revision", ref fRevision, value); }
        }
        string fDescription;
        [Size(1000)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fImageDestination;
        [Size(200)]
        public string ImageDestination
        {
            get { return fImageDestination; }
            set { SetPropertyValue<string>("ImageDestination", ref fImageDestination, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"CAT_CatalogueReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
        [Association(@"CAT_CategoryReferencesCAT_Catalogue", typeof(CAT_Category))]
        public XPCollection<CAT_Category> CAT_Categorys { get { return GetCollection<CAT_Category>("CAT_Categorys"); } }
    }

}
