//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_GLX.GLX_History")]
    public partial class GLX_History : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        SYS_Period fPeriodId;
        [Association(@"GLX_HistoryReferencesSYS_Period")]
        public SYS_Period PeriodId
        {
            get { return fPeriodId; }
            set { SetPropertyValue<SYS_Period>("PeriodId", ref fPeriodId, value); }
        }
        SYS_Entity fEntityId;
        [Association(@"GLX_HistoryReferencesSYS_Entity")]
        public SYS_Entity EntityId
        {
            get { return fEntityId; }
            set { SetPropertyValue<SYS_Entity>("EntityId", ref fEntityId, value); }
        }
        GLX_Aging fAgingId;
        [Association(@"GLX_HistoryReferencesGLX_Aging")]
        public GLX_Aging AgingId
        {
            get { return fAgingId; }
            set { SetPropertyValue<GLX_Aging>("AgingId", ref fAgingId, value); }
        }
        decimal fAmount;
        public decimal Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<decimal>("Amount", ref fAmount, value); }
        }
    }

}
