//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_GLX.GLX_Account")]
    public partial class GLX_Account : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        SYS_Entity fEntityId;
        [Association(@"GLX_AccountReferencesSYS_Entity")]
        public SYS_Entity EntityId
        {
            get { return fEntityId; }
            set { SetPropertyValue<SYS_Entity>("EntityId", ref fEntityId, value); }
        }
        CDS.DataAccessLayer.XPO.Enums.GLX_Type fAccountTypeId;
        public CDS.DataAccessLayer.XPO.Enums.GLX_Type AccountTypeId
        {
            get { return fAccountTypeId; }
            set { SetPropertyValue<CDS.DataAccessLayer.XPO.Enums.GLX_Type>("AccountTypeId", ref fAccountTypeId, value); }
        }
        SYS_Entity fCenterId;
        [Association(@"GLX_AccountReferencesSYS_Entity1")]
        public SYS_Entity CenterId
        {
            get { return fCenterId; }
            set { SetPropertyValue<SYS_Entity>("CenterId", ref fCenterId, value); }
        }
        bool fAgingAccount;
        public bool AgingAccount
        {
            get { return fAgingAccount; }
            set { SetPropertyValue<bool>("AgingAccount", ref fAgingAccount, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"GLX_AccountReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
        SYS_Entity fControlId;
        [Association(@"GLX_AccountReferencesSYS_Entity2")]
        public SYS_Entity ControlId
        {
            get { return fControlId; }
            set { SetPropertyValue<SYS_Entity>("ControlId", ref fControlId, value); }
        }
        SYS_Entity fMasterControlId;
        [Association(@"GLX_AccountReferencesSYS_Entity3")]
        public SYS_Entity MasterControlId
        {
            get { return fMasterControlId; }
            set { SetPropertyValue<SYS_Entity>("MasterControlId", ref fMasterControlId, value); }
        }
        string fBalanceGroup;
        [Size(10)]
        public string BalanceGroup
        {
            get { return fBalanceGroup; }
            set { SetPropertyValue<string>("BalanceGroup", ref fBalanceGroup, value); }
        }
    }

}
