//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_GLX.GLX_Header")]
    public partial class GLX_Header : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        SYS_Period fPeriodId;
        [Association(@"GLX_HeaderReferencesSYS_Period")]
        public SYS_Period PeriodId
        {
            get { return fPeriodId; }
            set { SetPropertyValue<SYS_Period>("PeriodId", ref fPeriodId, value); }
        }
        CDS.DataAccessLayer.XPO.Enums.SYS_Status fStatusId;
        public CDS.DataAccessLayer.XPO.Enums.SYS_Status StatusId
        {
            get { return fStatusId; }
            set { SetPropertyValue<CDS.DataAccessLayer.XPO.Enums.SYS_Status>("StatusId", ref fStatusId, value); }
        }
        SYS_Tracking fTrackId;
        [Association(@"GLX_HeaderReferencesSYS_Tracking")]
        public SYS_Tracking TrackId
        {
            get { return fTrackId; }
            set { SetPropertyValue<SYS_Tracking>("TrackId", ref fTrackId, value); }
        }
        CDS.DataAccessLayer.XPO.Enums.GLX_JournalType fJournalTypeId;
        public CDS.DataAccessLayer.XPO.Enums.GLX_JournalType JournalTypeId
        {
            get { return fJournalTypeId; }
            set { SetPropertyValue<CDS.DataAccessLayer.XPO.Enums.GLX_JournalType>("JournalTypeId", ref fJournalTypeId, value); }
        }
        string fReference;
        [Size(50)]
        public string Reference
        {
            get { return fReference; }
            set { SetPropertyValue<string>("Reference", ref fReference, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
        DateTime fPostedDate;
        public DateTime PostedDate
        {
            get { return fPostedDate; }
            set { SetPropertyValue<DateTime>("PostedDate", ref fPostedDate, value); }
        }
        string fTitle;
        [Size(151)]
        [NonPersistent]
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>("Title", ref fTitle, value); }
        }
        DateTime fCreatedOn;
        [NonPersistent]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"GLX_HeaderReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
        long fReferenceId;
        public long ReferenceId
        {
            get { return fReferenceId; }
            set { SetPropertyValue<long>("ReferenceId", ref fReferenceId, value); }
        }
        [Association(@"GLX_LineReferencesGLX_Header", typeof(GLX_Line))]
        public XPCollection<GLX_Line> GLX_Lines { get { return GetCollection<GLX_Line>("GLX_Lines"); } }
    }

}
