//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_IBO.IBO_History")]
    public partial class IBO_History : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        IBO_Item fItemId;
        [Association(@"IBO_HistoryReferencesIBO_Item")]
        public IBO_Item ItemId
        {
            get { return fItemId; }
            set { SetPropertyValue<IBO_Item>("ItemId", ref fItemId, value); }
        }
        SYS_Period fPeriodId;
        [Association(@"IBO_HistoryReferencesSYS_Period")]
        public SYS_Period PeriodId
        {
            get { return fPeriodId; }
            set { SetPropertyValue<SYS_Period>("PeriodId", ref fPeriodId, value); }
        }
        decimal fOnHand;
        public decimal OnHand
        {
            get { return fOnHand; }
            set { SetPropertyValue<decimal>("OnHand", ref fOnHand, value); }
        }
        decimal fUnitAverage;
        public decimal UnitAverage
        {
            get { return fUnitAverage; }
            set { SetPropertyValue<decimal>("UnitAverage", ref fUnitAverage, value); }
        }
    }

}
