//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_ITM.ITM_StockTakeItem")]
    public partial class ITM_StockTakeItem : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        ITM_StockTake fStockTakeId;
        [Association(@"ITM_StockTakeItemReferencesITM_StockTake")]
        public ITM_StockTake StockTakeId
        {
            get { return fStockTakeId; }
            set { SetPropertyValue<ITM_StockTake>("StockTakeId", ref fStockTakeId, value); }
        }
        SYS_Entity fInventoryId;
        [Association(@"ITM_StockTakeItemReferencesSYS_Entity")]
        public SYS_Entity InventoryId
        {
            get { return fInventoryId; }
            set { SetPropertyValue<SYS_Entity>("InventoryId", ref fInventoryId, value); }
        }
        long fLineNumber;
        public long LineNumber
        {
            get { return fLineNumber; }
            set { SetPropertyValue<long>("LineNumber", ref fLineNumber, value); }
        }
        int fPageNumber;
        public int PageNumber
        {
            get { return fPageNumber; }
            set { SetPropertyValue<int>("PageNumber", ref fPageNumber, value); }
        }
        decimal fOnHand;
        public decimal OnHand
        {
            get { return fOnHand; }
            set { SetPropertyValue<decimal>("OnHand", ref fOnHand, value); }
        }
        decimal fQuantityCount1;
        public decimal QuantityCount1
        {
            get { return fQuantityCount1; }
            set { SetPropertyValue<decimal>("QuantityCount1", ref fQuantityCount1, value); }
        }
        decimal fQuantityCount2;
        public decimal QuantityCount2
        {
            get { return fQuantityCount2; }
            set { SetPropertyValue<decimal>("QuantityCount2", ref fQuantityCount2, value); }
        }
        decimal fUnitPrice;
        public decimal UnitPrice
        {
            get { return fUnitPrice; }
            set { SetPropertyValue<decimal>("UnitPrice", ref fUnitPrice, value); }
        }
        decimal fUnitCost;
        public decimal UnitCost
        {
            get { return fUnitCost; }
            set { SetPropertyValue<decimal>("UnitCost", ref fUnitCost, value); }
        }
        decimal fUnitAverage;
        public decimal UnitAverage
        {
            get { return fUnitAverage; }
            set { SetPropertyValue<decimal>("UnitAverage", ref fUnitAverage, value); }
        }
        bool fSuccessfullyChanged;
        public bool SuccessfullyChanged
        {
            get { return fSuccessfullyChanged; }
            set { SetPropertyValue<bool>("SuccessfullyChanged", ref fSuccessfullyChanged, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"ITM_StockTakeItemReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
    }

}
