//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_SYS.SYS_Site")]
    public partial class SYS_Site : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        SYS_Entity fEntityId;
        [Association(@"SYS_SiteReferencesSYS_Entity")]
        public SYS_Entity EntityId
        {
            get { return fEntityId; }
            set { SetPropertyValue<SYS_Entity>("EntityId", ref fEntityId, value); }
        }
        SYS_Address fBillingAddress;
        [Association(@"SYS_SiteReferencesSYS_Address")]
        public SYS_Address BillingAddress
        {
            get { return fBillingAddress; }
            set { SetPropertyValue<SYS_Address>("BillingAddress", ref fBillingAddress, value); }
        }
        SYS_Address fShippingAddress;
        [Association(@"SYS_SiteReferencesSYS_Address1")]
        public SYS_Address ShippingAddress
        {
            get { return fShippingAddress; }
            set { SetPropertyValue<SYS_Address>("ShippingAddress", ref fShippingAddress, value); }
        }
        string fTelephone;
        [Size(50)]
        public string Telephone
        {
            get { return fTelephone; }
            set { SetPropertyValue<string>("Telephone", ref fTelephone, value); }
        }
        string fEmailAddress;
        [Size(50)]
        public string EmailAddress
        {
            get { return fEmailAddress; }
            set { SetPropertyValue<string>("EmailAddress", ref fEmailAddress, value); }
        }
        string fRegistrationNumber;
        [Size(50)]
        public string RegistrationNumber
        {
            get { return fRegistrationNumber; }
            set { SetPropertyValue<string>("RegistrationNumber", ref fRegistrationNumber, value); }
        }
        decimal fVatPercentage;
        public decimal VatPercentage
        {
            get { return fVatPercentage; }
            set { SetPropertyValue<decimal>("VatPercentage", ref fVatPercentage, value); }
        }
        string fVatNumber;
        [Size(50)]
        public string VatNumber
        {
            get { return fVatNumber; }
            set { SetPropertyValue<string>("VatNumber", ref fVatNumber, value); }
        }
        string fCurrency;
        [Size(50)]
        public string Currency
        {
            get { return fCurrency; }
            set { SetPropertyValue<string>("Currency", ref fCurrency, value); }
        }
        short fCashierRefreshIntervals;
        public short CashierRefreshIntervals
        {
            get { return fCashierRefreshIntervals; }
            set { SetPropertyValue<short>("CashierRefreshIntervals", ref fCashierRefreshIntervals, value); }
        }
        string fSMTPServerLocation;
        [Size(50)]
        public string SMTPServerLocation
        {
            get { return fSMTPServerLocation; }
            set { SetPropertyValue<string>("SMTPServerLocation", ref fSMTPServerLocation, value); }
        }
        string fAccountEmailAddress;
        [Size(50)]
        public string AccountEmailAddress
        {
            get { return fAccountEmailAddress; }
            set { SetPropertyValue<string>("AccountEmailAddress", ref fAccountEmailAddress, value); }
        }
        string fAccountEmailUsername;
        [Size(50)]
        public string AccountEmailUsername
        {
            get { return fAccountEmailUsername; }
            set { SetPropertyValue<string>("AccountEmailUsername", ref fAccountEmailUsername, value); }
        }
        string fAccountEmailPassword;
        [Size(50)]
        public string AccountEmailPassword
        {
            get { return fAccountEmailPassword; }
            set { SetPropertyValue<string>("AccountEmailPassword", ref fAccountEmailPassword, value); }
        }
        string fAccountEmailDomain;
        [Size(50)]
        public string AccountEmailDomain
        {
            get { return fAccountEmailDomain; }
            set { SetPropertyValue<string>("AccountEmailDomain", ref fAccountEmailDomain, value); }
        }
        string fAccountEmailBCCAddress;
        [Size(50)]
        public string AccountEmailBCCAddress
        {
            get { return fAccountEmailBCCAddress; }
            set { SetPropertyValue<string>("AccountEmailBCCAddress", ref fAccountEmailBCCAddress, value); }
        }
        string fDocumentEmailAddress;
        [Size(50)]
        public string DocumentEmailAddress
        {
            get { return fDocumentEmailAddress; }
            set { SetPropertyValue<string>("DocumentEmailAddress", ref fDocumentEmailAddress, value); }
        }
        string fDocumentEmailUsername;
        [Size(50)]
        public string DocumentEmailUsername
        {
            get { return fDocumentEmailUsername; }
            set { SetPropertyValue<string>("DocumentEmailUsername", ref fDocumentEmailUsername, value); }
        }
        string fDocumentEmailPassword;
        [Size(50)]
        public string DocumentEmailPassword
        {
            get { return fDocumentEmailPassword; }
            set { SetPropertyValue<string>("DocumentEmailPassword", ref fDocumentEmailPassword, value); }
        }
        string fDocumentEmailDomain;
        [Size(50)]
        public string DocumentEmailDomain
        {
            get { return fDocumentEmailDomain; }
            set { SetPropertyValue<string>("DocumentEmailDomain", ref fDocumentEmailDomain, value); }
        }
        string fDocumentEmailBCCAddress;
        [Size(50)]
        public string DocumentEmailBCCAddress
        {
            get { return fDocumentEmailBCCAddress; }
            set { SetPropertyValue<string>("DocumentEmailBCCAddress", ref fDocumentEmailBCCAddress, value); }
        }
        string fProxyServerLocation;
        [Size(50)]
        public string ProxyServerLocation
        {
            get { return fProxyServerLocation; }
            set { SetPropertyValue<string>("ProxyServerLocation", ref fProxyServerLocation, value); }
        }
        string fProxyServerUsername;
        [Size(50)]
        public string ProxyServerUsername
        {
            get { return fProxyServerUsername; }
            set { SetPropertyValue<string>("ProxyServerUsername", ref fProxyServerUsername, value); }
        }
        string fProxyServerPassword;
        [Size(50)]
        public string ProxyServerPassword
        {
            get { return fProxyServerPassword; }
            set { SetPropertyValue<string>("ProxyServerPassword", ref fProxyServerPassword, value); }
        }
        string fPrintServerLocation;
        [Size(200)]
        public string PrintServerLocation
        {
            get { return fPrintServerLocation; }
            set { SetPropertyValue<string>("PrintServerLocation", ref fPrintServerLocation, value); }
        }
        string fBankName;
        [Size(50)]
        public string BankName
        {
            get { return fBankName; }
            set { SetPropertyValue<string>("BankName", ref fBankName, value); }
        }
        string fBankBranch;
        [Size(50)]
        public string BankBranch
        {
            get { return fBankBranch; }
            set { SetPropertyValue<string>("BankBranch", ref fBankBranch, value); }
        }
        string fBankCode;
        [Size(50)]
        public string BankCode
        {
            get { return fBankCode; }
            set { SetPropertyValue<string>("BankCode", ref fBankCode, value); }
        }
        string fBankAccountNumber;
        [Size(50)]
        public string BankAccountNumber
        {
            get { return fBankAccountNumber; }
            set { SetPropertyValue<string>("BankAccountNumber", ref fBankAccountNumber, value); }
        }
        string fDefaultMessageDocument;
        [Size(1000)]
        public string DefaultMessageDocument
        {
            get { return fDefaultMessageDocument; }
            set { SetPropertyValue<string>("DefaultMessageDocument", ref fDefaultMessageDocument, value); }
        }
        string fDefaultMessageStatement;
        [Size(1000)]
        public string DefaultMessageStatement
        {
            get { return fDefaultMessageStatement; }
            set { SetPropertyValue<string>("DefaultMessageStatement", ref fDefaultMessageStatement, value); }
        }
        SYS_Printer fPrinterBarcode;
        [Association(@"SYS_SiteReferencesSYS_Printer")]
        public SYS_Printer PrinterBarcode
        {
            get { return fPrinterBarcode; }
            set { SetPropertyValue<SYS_Printer>("PrinterBarcode", ref fPrinterBarcode, value); }
        }
        SYS_Printer fPrinterPicker;
        [Association(@"SYS_SiteReferencesSYS_Printer1")]
        public SYS_Printer PrinterPicker
        {
            get { return fPrinterPicker; }
            set { SetPropertyValue<SYS_Printer>("PrinterPicker", ref fPrinterPicker, value); }
        }
        SYS_Printer fPrinterReceipt;
        [Association(@"SYS_SiteReferencesSYS_Printer2")]
        public SYS_Printer PrinterReceipt
        {
            get { return fPrinterReceipt; }
            set { SetPropertyValue<SYS_Printer>("PrinterReceipt", ref fPrinterReceipt, value); }
        }
        string fUpdateURL;
        [Size(50)]
        public string UpdateURL
        {
            get { return fUpdateURL; }
            set { SetPropertyValue<string>("UpdateURL", ref fUpdateURL, value); }
        }
        bool fMinimizeNavigation;
        public bool MinimizeNavigation
        {
            get { return fMinimizeNavigation; }
            set { SetPropertyValue<bool>("MinimizeNavigation", ref fMinimizeNavigation, value); }
        }
        string fUpdateCheckTime;
        [Size(50)]
        public string UpdateCheckTime
        {
            get { return fUpdateCheckTime; }
            set { SetPropertyValue<string>("UpdateCheckTime", ref fUpdateCheckTime, value); }
        }
        string fPaymentAccounts;
        [Size(1000)]
        public string PaymentAccounts
        {
            get { return fPaymentAccounts; }
            set { SetPropertyValue<string>("PaymentAccounts", ref fPaymentAccounts, value); }
        }
        bool fUseBarcodes;
        public bool UseBarcodes
        {
            get { return fUseBarcodes; }
            set { SetPropertyValue<bool>("UseBarcodes", ref fUseBarcodes, value); }
        }
        bool fUseLabels;
        public bool UseLabels
        {
            get { return fUseLabels; }
            set { SetPropertyValue<bool>("UseLabels", ref fUseLabels, value); }
        }
        bool fCopyInvoiceOrderNumbertoCreditNote;
        public bool CopyInvoiceOrderNumbertoCreditNote
        {
            get { return fCopyInvoiceOrderNumbertoCreditNote; }
            set { SetPropertyValue<bool>("CopyInvoiceOrderNumbertoCreditNote", ref fCopyInvoiceOrderNumbertoCreditNote, value); }
        }
        bool fAutoWriteoffOpenItemCredits;
        public bool AutoWriteoffOpenItemCredits
        {
            get { return fAutoWriteoffOpenItemCredits; }
            set { SetPropertyValue<bool>("AutoWriteoffOpenItemCredits", ref fAutoWriteoffOpenItemCredits, value); }
        }
        byte fNegativeDiscountEffects;
        public byte NegativeDiscountEffects
        {
            get { return fNegativeDiscountEffects; }
            set { SetPropertyValue<byte>("NegativeDiscountEffects", ref fNegativeDiscountEffects, value); }
        }
        bool fNotifyonZeroMarkupSale;
        public bool NotifyonZeroMarkupSale
        {
            get { return fNotifyonZeroMarkupSale; }
            set { SetPropertyValue<bool>("NotifyonZeroMarkupSale", ref fNotifyonZeroMarkupSale, value); }
        }
        bool fNotifyonZeroProfitSale;
        public bool NotifyonZeroProfitSale
        {
            get { return fNotifyonZeroProfitSale; }
            set { SetPropertyValue<bool>("NotifyonZeroProfitSale", ref fNotifyonZeroProfitSale, value); }
        }
        byte fQuoteValidDays;
        public byte QuoteValidDays
        {
            get { return fQuoteValidDays; }
            set { SetPropertyValue<byte>("QuoteValidDays", ref fQuoteValidDays, value); }
        }
        byte fQuoteValidMax;
        public byte QuoteValidMax
        {
            get { return fQuoteValidMax; }
            set { SetPropertyValue<byte>("QuoteValidMax", ref fQuoteValidMax, value); }
        }
        bool fNotifyonBackOrder;
        public bool NotifyonBackOrder
        {
            get { return fNotifyonBackOrder; }
            set { SetPropertyValue<bool>("NotifyonBackOrder", ref fNotifyonBackOrder, value); }
        }
        decimal fRoundingAmount;
        public decimal RoundingAmount
        {
            get { return fRoundingAmount; }
            set { SetPropertyValue<decimal>("RoundingAmount", ref fRoundingAmount, value); }
        }
        bool fCashierPaymentsFullAmount;
        public bool CashierPaymentsFullAmount
        {
            get { return fCashierPaymentsFullAmount; }
            set { SetPropertyValue<bool>("CashierPaymentsFullAmount", ref fCashierPaymentsFullAmount, value); }
        }
        byte fCODAccountLimit;
        public byte CODAccountLimit
        {
            get { return fCODAccountLimit; }
            set { SetPropertyValue<byte>("CODAccountLimit", ref fCODAccountLimit, value); }
        }
        byte fDebtorGracePeriod;
        public byte DebtorGracePeriod
        {
            get { return fDebtorGracePeriod; }
            set { SetPropertyValue<byte>("DebtorGracePeriod", ref fDebtorGracePeriod, value); }
        }
        decimal fDefaultInterestCharged;
        public decimal DefaultInterestCharged
        {
            get { return fDefaultInterestCharged; }
            set { SetPropertyValue<decimal>("DefaultInterestCharged", ref fDefaultInterestCharged, value); }
        }
        byte fMonthWeight3;
        public byte MonthWeight3
        {
            get { return fMonthWeight3; }
            set { SetPropertyValue<byte>("MonthWeight3", ref fMonthWeight3, value); }
        }
        byte fMonthWeight6;
        public byte MonthWeight6
        {
            get { return fMonthWeight6; }
            set { SetPropertyValue<byte>("MonthWeight6", ref fMonthWeight6, value); }
        }
        byte fMonthWeight12;
        public byte MonthWeight12
        {
            get { return fMonthWeight12; }
            set { SetPropertyValue<byte>("MonthWeight12", ref fMonthWeight12, value); }
        }
        byte fMonthWeight24;
        public byte MonthWeight24
        {
            get { return fMonthWeight24; }
            set { SetPropertyValue<byte>("MonthWeight24", ref fMonthWeight24, value); }
        }
        byte fMonthWeight36;
        public byte MonthWeight36
        {
            get { return fMonthWeight36; }
            set { SetPropertyValue<byte>("MonthWeight36", ref fMonthWeight36, value); }
        }
        decimal fFixedOrderCost;
        public decimal FixedOrderCost
        {
            get { return fFixedOrderCost; }
            set { SetPropertyValue<decimal>("FixedOrderCost", ref fFixedOrderCost, value); }
        }
        byte fMaxOrderLines;
        public byte MaxOrderLines
        {
            get { return fMaxOrderLines; }
            set { SetPropertyValue<byte>("MaxOrderLines", ref fMaxOrderLines, value); }
        }
        byte fSafetyStockPeriod;
        public byte SafetyStockPeriod
        {
            get { return fSafetyStockPeriod; }
            set { SetPropertyValue<byte>("SafetyStockPeriod", ref fSafetyStockPeriod, value); }
        }
        string fDistributionNumber;
        [Size(50)]
        public string DistributionNumber
        {
            get { return fDistributionNumber; }
            set { SetPropertyValue<string>("DistributionNumber", ref fDistributionNumber, value); }
        }
        string fBackupLocation;
        [Size(200)]
        public string BackupLocation
        {
            get { return fBackupLocation; }
            set { SetPropertyValue<string>("BackupLocation", ref fBackupLocation, value); }
        }
    }

}
