//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_SYS.SYS_DOC_Header")]
    public partial class SYS_DOC_Header : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        SYS_Tracking fTrackId;
        [Association(@"SYS_DOC_HeaderReferencesSYS_Tracking")]
        public SYS_Tracking TrackId
        {
            get { return fTrackId; }
            set { SetPropertyValue<SYS_Tracking>("TrackId", ref fTrackId, value); }
        }
        CDS.DataAccessLayer.XPO.Enums.SYS_DOC_Type fTypeId;
        public CDS.DataAccessLayer.XPO.Enums.SYS_DOC_Type TypeId
        {
            get { return fTypeId; }
            set { SetPropertyValue<CDS.DataAccessLayer.XPO.Enums.SYS_DOC_Type>("TypeId", ref fTypeId, value); }
        }
        long fDocumentNumber;
        public long DocumentNumber
        {
            get { return fDocumentNumber; }
            set { SetPropertyValue<long>("DocumentNumber", ref fDocumentNumber, value); }
        }
        string fComment;
        [Size(1000)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>("Comment", ref fComment, value); }
        }
        DateTime fCreatedOn;
        [NonPersistent]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"SYS_DOC_HeaderReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
        [Association(@"CAL_AttachmentReferencesSYS_DOC_Header", typeof(CAL_Attachment))]
        public XPCollection<CAL_Attachment> CAL_Attachments { get { return GetCollection<CAL_Attachment>("CAL_Attachments"); } }
        [Association(@"CAL_CalendarReferencesSYS_DOC_Header", typeof(CAL_Calendar))]
        public XPCollection<CAL_Calendar> CAL_Calendars { get { return GetCollection<CAL_Calendar>("CAL_Calendars"); } }
        [Association(@"ITM_BOM_DocumentReferencesSYS_DOC_Header", typeof(ITM_BOM_Document))]
        public XPCollection<ITM_BOM_Document> ITM_BOM_Documents { get { return GetCollection<ITM_BOM_Document>("ITM_BOM_Documents"); } }
        [Association(@"CDS_JOB_JOB_HeaderReferencesSYS_DOC_Header", typeof(JOB_Header))]
        public XPCollection<JOB_Header> CDS_JOB_JOB_Headers { get { return GetCollection<JOB_Header>("CDS_JOB_JOB_Headers"); } }
        [Association(@"ORG_TRX_HeaderReferencesSYS_DOC_Header", typeof(ORG_TRX_Header))]
        public XPCollection<ORG_TRX_Header> ORG_TRX_Headers { get { return GetCollection<ORG_TRX_Header>("ORG_TRX_Headers"); } }
        [Association(@"SYS_DOC_LineReferencesSYS_DOC_Header", typeof(SYS_DOC_Line))]
        public XPCollection<SYS_DOC_Line> SYS_DOC_Lines { get { return GetCollection<SYS_DOC_Line>("SYS_DOC_Lines"); } }
    }

}
