//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_AOR.AOR_OrderLine")]
    public partial class AOR_OrderLine : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        AOR_Order fOrderId;
        [Association(@"AOR_OrderLineReferencesAOR_Order")]
        public AOR_Order OrderId
        {
            get { return fOrderId; }
            set { SetPropertyValue<AOR_Order>("OrderId", ref fOrderId, value); }
        }
        SYS_Entity fSupplierId;
        [Association(@"AOR_OrderLineReferencesSYS_Entity1")]
        public SYS_Entity SupplierId
        {
            get { return fSupplierId; }
            set { SetPropertyValue<SYS_Entity>("SupplierId", ref fSupplierId, value); }
        }
        SYS_Entity fInventoryId;
        [Association(@"AOR_OrderLineReferencesSYS_Entity")]
        public SYS_Entity InventoryId
        {
            get { return fInventoryId; }
            set { SetPropertyValue<SYS_Entity>("InventoryId", ref fInventoryId, value); }
        }
        string fSite;
        [Size(50)]
        public string Site
        {
            get { return fSite; }
            set { SetPropertyValue<string>("Site", ref fSite, value); }
        }
        string fSupplier;
        [Size(50)]
        public string Supplier
        {
            get { return fSupplier; }
            set { SetPropertyValue<string>("Supplier", ref fSupplier, value); }
        }
        string fShortName;
        [Size(50)]
        public string ShortName
        {
            get { return fShortName; }
            set { SetPropertyValue<string>("ShortName", ref fShortName, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        decimal fSafetyStock;
        public decimal SafetyStock
        {
            get { return fSafetyStock; }
            set { SetPropertyValue<decimal>("SafetyStock", ref fSafetyStock, value); }
        }
        decimal fOnHand;
        public decimal OnHand
        {
            get { return fOnHand; }
            set { SetPropertyValue<decimal>("OnHand", ref fOnHand, value); }
        }
        decimal fOnReserve;
        public decimal OnReserve
        {
            get { return fOnReserve; }
            set { SetPropertyValue<decimal>("OnReserve", ref fOnReserve, value); }
        }
        decimal fOnOrder;
        public decimal OnOrder
        {
            get { return fOnOrder; }
            set { SetPropertyValue<decimal>("OnOrder", ref fOnOrder, value); }
        }
        decimal fUnitCost;
        public decimal UnitCost
        {
            get { return fUnitCost; }
            set { SetPropertyValue<decimal>("UnitCost", ref fUnitCost, value); }
        }
        decimal fUnitAverage;
        public decimal UnitAverage
        {
            get { return fUnitAverage; }
            set { SetPropertyValue<decimal>("UnitAverage", ref fUnitAverage, value); }
        }
        decimal fUnitPrice;
        public decimal UnitPrice
        {
            get { return fUnitPrice; }
            set { SetPropertyValue<decimal>("UnitPrice", ref fUnitPrice, value); }
        }
        decimal fAvgDemand;
        public decimal AvgDemand
        {
            get { return fAvgDemand; }
            set { SetPropertyValue<decimal>("AvgDemand", ref fAvgDemand, value); }
        }
        decimal fEoq;
        public decimal Eoq
        {
            get { return fEoq; }
            set { SetPropertyValue<decimal>("Eoq", ref fEoq, value); }
        }
        decimal fOrderPoint;
        public decimal OrderPoint
        {
            get { return fOrderPoint; }
            set { SetPropertyValue<decimal>("OrderPoint", ref fOrderPoint, value); }
        }
        decimal fOrderAmountCalculated;
        public decimal OrderAmountCalculated
        {
            get { return fOrderAmountCalculated; }
            set { SetPropertyValue<decimal>("OrderAmountCalculated", ref fOrderAmountCalculated, value); }
        }
        decimal fOrderAmount;
        public decimal OrderAmount
        {
            get { return fOrderAmount; }
            set { SetPropertyValue<decimal>("OrderAmount", ref fOrderAmount, value); }
        }
        decimal fTotal;
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>("Total", ref fTotal, value); }
        }
        decimal fTotalTax;
        public decimal TotalTax
        {
            get { return fTotalTax; }
            set { SetPropertyValue<decimal>("TotalTax", ref fTotalTax, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"AOR_OrderLineReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
    }

}
