//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_CAL.CAL_Calendar")]
    public partial class CAL_Calendar : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        short fLabelId;
        public short LabelId
        {
            get { return fLabelId; }
            set { SetPropertyValue<short>("LabelId", ref fLabelId, value); }
        }
        string fSubject;
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>("Subject", ref fSubject, value); }
        }
        string fDescription;
        [Size(200)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        DateTime fStartDate;
        public DateTime StartDate
        {
            get { return fStartDate; }
            set { SetPropertyValue<DateTime>("StartDate", ref fStartDate, value); }
        }
        DateTime fEndDate;
        public DateTime EndDate
        {
            get { return fEndDate; }
            set { SetPropertyValue<DateTime>("EndDate", ref fEndDate, value); }
        }
        bool fAllDay;
        public bool AllDay
        {
            get { return fAllDay; }
            set { SetPropertyValue<bool>("AllDay", ref fAllDay, value); }
        }
        string fLocation;
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>("Location", ref fLocation, value); }
        }
        decimal fPercentComplete;
        public decimal PercentComplete
        {
            get { return fPercentComplete; }
            set { SetPropertyValue<decimal>("PercentComplete", ref fPercentComplete, value); }
        }
        string fRecurrenceInfo;
        [Size(SizeAttribute.Unlimited)]
        public string RecurrenceInfo
        {
            get { return fRecurrenceInfo; }
            set { SetPropertyValue<string>("RecurrenceInfo", ref fRecurrenceInfo, value); }
        }
        string fReminderInfo;
        [Size(SizeAttribute.Unlimited)]
        public string ReminderInfo
        {
            get { return fReminderInfo; }
            set { SetPropertyValue<string>("ReminderInfo", ref fReminderInfo, value); }
        }
        long fResourceId;
        public long ResourceId
        {
            get { return fResourceId; }
            set { SetPropertyValue<long>("ResourceId", ref fResourceId, value); }
        }
        short fStatusId;
        public short StatusId
        {
            get { return fStatusId; }
            set { SetPropertyValue<short>("StatusId", ref fStatusId, value); }
        }
        short fTypeId;
        public short TypeId
        {
            get { return fTypeId; }
            set { SetPropertyValue<short>("TypeId", ref fTypeId, value); }
        }
        SYS_DOC_Header fDocumentId;
        [Association(@"CAL_CalendarReferencesSYS_DOC_Header")]
        public SYS_DOC_Header DocumentId
        {
            get { return fDocumentId; }
            set { SetPropertyValue<SYS_DOC_Header>("DocumentId", ref fDocumentId, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"CAL_CalendarReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
        string fVehicle;
        [Size(50)]
        public string Vehicle
        {
            get { return fVehicle; }
            set { SetPropertyValue<string>("Vehicle", ref fVehicle, value); }
        }
        string fRegistration;
        [Size(50)]
        public string Registration
        {
            get { return fRegistration; }
            set { SetPropertyValue<string>("Registration", ref fRegistration, value); }
        }
        string fMileage;
        [Size(50)]
        public string Mileage
        {
            get { return fMileage; }
            set { SetPropertyValue<string>("Mileage", ref fMileage, value); }
        }
        string fContact;
        [Size(50)]
        public string Contact
        {
            get { return fContact; }
            set { SetPropertyValue<string>("Contact", ref fContact, value); }
        }
        string fTelephone;
        [Size(50)]
        public string Telephone
        {
            get { return fTelephone; }
            set { SetPropertyValue<string>("Telephone", ref fTelephone, value); }
        }
        SYS_Entity fEntityId;
        [Association(@"CAL_CalendarReferencesSYS_Entity")]
        public SYS_Entity EntityId
        {
            get { return fEntityId; }
            set { SetPropertyValue<SYS_Entity>("EntityId", ref fEntityId, value); }
        }
        [Association(@"CAL_AttachmentReferencesCAL_Calendar", typeof(CAL_Attachment))]
        public XPCollection<CAL_Attachment> CAL_Attachments { get { return GetCollection<CAL_Attachment>("CAL_Attachments"); } }
    }

}
