//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_GLX.GLX_BulkEntryRule")]
    public partial class GLX_BulkEntryRule : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        SYS_Entity fEntityId;
        [Association(@"GLX_BulkEntryRuleReferencesSYS_Entity")]
        public SYS_Entity EntityId
        {
            get { return fEntityId; }
            set { SetPropertyValue<SYS_Entity>("EntityId", ref fEntityId, value); }
        }
        SYS_Entity fEntityContraId;
        [Association(@"GLX_BulkEntryRuleReferencesSYS_Entity1")]
        public SYS_Entity EntityContraId
        {
            get { return fEntityContraId; }
            set { SetPropertyValue<SYS_Entity>("EntityContraId", ref fEntityContraId, value); }
        }
        GLX_Tax fTaxId;
        [Association(@"GLX_BulkEntryRuleReferencesGLX_Tax")]
        public GLX_Tax TaxId
        {
            get { return fTaxId; }
            set { SetPropertyValue<GLX_Tax>("TaxId", ref fTaxId, value); }
        }
        string fEntryRule;
        [Size(200)]
        public string EntryRule
        {
            get { return fEntryRule; }
            set { SetPropertyValue<string>("EntryRule", ref fEntryRule, value); }
        }
        char fEntryAction;
        public char EntryAction
        {
            get { return fEntryAction; }
            set { SetPropertyValue<char>("EntryAction", ref fEntryAction, value); }
        }
        short fPriority;
        public short Priority
        {
            get { return fPriority; }
            set { SetPropertyValue<short>("Priority", ref fPriority, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"GLX_BulkEntryRuleReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
    }

}
