//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_GLX.GLX_Tax")]
    public partial class GLX_Tax : XPLiteObject
    {
        short fId;
        [Key]
        public short Id
        {
            get { return fId; }
            set { SetPropertyValue<short>("Id", ref fId, value); }
        }
        SYS_Entity fEntityId;
        [Association(@"GLX_TaxReferencesSYS_Entity")]
        public SYS_Entity EntityId
        {
            get { return fEntityId; }
            set { SetPropertyValue<SYS_Entity>("EntityId", ref fEntityId, value); }
        }
        string fCode;
        [Size(50)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>("Code", ref fCode, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fDescription;
        [Size(2000)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"GLX_TaxReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
        string fTitle;
        [Size(103)]
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>("Title", ref fTitle, value); }
        }
        decimal fAmount;
        public decimal Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<decimal>("Amount", ref fAmount, value); }
        }
        [Association(@"GLX_BulkEntryRuleReferencesGLX_Tax", typeof(GLX_BulkEntryRule))]
        public XPCollection<GLX_BulkEntryRule> GLX_BulkEntryRules { get { return GetCollection<GLX_BulkEntryRule>("GLX_BulkEntryRules"); } }
        [Association(@"GLX_LineReferencesGLX_Tax", typeof(GLX_Line))]
        public XPCollection<GLX_Line> GLX_Lines { get { return GetCollection<GLX_Line>("GLX_Lines"); } }
    }

}
