//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_IBO.IBO_Item")]
    public partial class IBO_Item : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        decimal fUnitCost;
        public decimal UnitCost
        {
            get { return fUnitCost; }
            set { SetPropertyValue<decimal>("UnitCost", ref fUnitCost, value); }
        }
        decimal fUnitPrice;
        public decimal UnitPrice
        {
            get { return fUnitPrice; }
            set { SetPropertyValue<decimal>("UnitPrice", ref fUnitPrice, value); }
        }
        decimal fUnitAverage;
        public decimal UnitAverage
        {
            get { return fUnitAverage; }
            set { SetPropertyValue<decimal>("UnitAverage", ref fUnitAverage, value); }
        }
        decimal fOnHand;
        public decimal OnHand
        {
            get { return fOnHand; }
            set { SetPropertyValue<decimal>("OnHand", ref fOnHand, value); }
        }
        string fCode;
        [Size(50)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>("Code", ref fCode, value); }
        }
        string fDescription;
        [Size(1000)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"IBO_ItemReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
        [Association(@"IBO_HistoryReferencesIBO_Item", typeof(IBO_History))]
        public XPCollection<IBO_History> IBO_Historys { get { return GetCollection<IBO_History>("IBO_Historys"); } }
        [Association(@"IBO_MovementReferencesIBO_Item", typeof(IBO_Movement))]
        public XPCollection<IBO_Movement> IBO_Movements { get { return GetCollection<IBO_Movement>("IBO_Movements"); } }
    }

}
