//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_ITM.ITM_Movement")]
    public partial class ITM_Movement : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        SYS_DOC_Line fLineId;
        [Association(@"ITM_MovementReferencesSYS_DOC_Line")]
        public SYS_DOC_Line LineId
        {
            get { return fLineId; }
            set { SetPropertyValue<SYS_DOC_Line>("LineId", ref fLineId, value); }
        }
        decimal fOnHand;
        public decimal OnHand
        {
            get { return fOnHand; }
            set { SetPropertyValue<decimal>("OnHand", ref fOnHand, value); }
        }
        decimal fOnOrder;
        public decimal OnOrder
        {
            get { return fOnOrder; }
            set { SetPropertyValue<decimal>("OnOrder", ref fOnOrder, value); }
        }
        decimal fOnReserve;
        public decimal OnReserve
        {
            get { return fOnReserve; }
            set { SetPropertyValue<decimal>("OnReserve", ref fOnReserve, value); }
        }
        decimal fUnitCost;
        public decimal UnitCost
        {
            get { return fUnitCost; }
            set { SetPropertyValue<decimal>("UnitCost", ref fUnitCost, value); }
        }
        decimal fUnitPrice;
        public decimal UnitPrice
        {
            get { return fUnitPrice; }
            set { SetPropertyValue<decimal>("UnitPrice", ref fUnitPrice, value); }
        }
        decimal fUnitAverage;
        public decimal UnitAverage
        {
            get { return fUnitAverage; }
            set { SetPropertyValue<decimal>("UnitAverage", ref fUnitAverage, value); }
        }
        decimal fNewUnitCost;
        public decimal NewUnitCost
        {
            get { return fNewUnitCost; }
            set { SetPropertyValue<decimal>("NewUnitCost", ref fNewUnitCost, value); }
        }
        decimal fNewUnitPrice;
        public decimal NewUnitPrice
        {
            get { return fNewUnitPrice; }
            set { SetPropertyValue<decimal>("NewUnitPrice", ref fNewUnitPrice, value); }
        }
        decimal fNewUnitAverage;
        public decimal NewUnitAverage
        {
            get { return fNewUnitAverage; }
            set { SetPropertyValue<decimal>("NewUnitAverage", ref fNewUnitAverage, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"ITM_MovementReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
    }

}
