//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_ITM.ITM_Inventory")]
    public partial class ITM_Inventory : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        SYS_Entity fEntityId;
        [Association(@"ITM_InventoryReferencesSYS_Entity")]
        public SYS_Entity EntityId
        {
            get { return fEntityId; }
            set { SetPropertyValue<SYS_Entity>("EntityId", ref fEntityId, value); }
        }
        SYS_Entity fCostofSalesId;
        [Association(@"ITM_InventoryReferencesSYS_Entity1")]
        public SYS_Entity CostofSalesId
        {
            get { return fCostofSalesId; }
            set { SetPropertyValue<SYS_Entity>("CostofSalesId", ref fCostofSalesId, value); }
        }
        SYS_Entity fInventoryId;
        [Association(@"ITM_InventoryReferencesSYS_Entity2")]
        public SYS_Entity InventoryId
        {
            get { return fInventoryId; }
            set { SetPropertyValue<SYS_Entity>("InventoryId", ref fInventoryId, value); }
        }
        string fComment;
        [Size(1000)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>("Comment", ref fComment, value); }
        }
        string fCategory;
        [Size(50)]
        public string Category
        {
            get { return fCategory; }
            set { SetPropertyValue<string>("Category", ref fCategory, value); }
        }
        string fSubCategory;
        [Size(50)]
        public string SubCategory
        {
            get { return fSubCategory; }
            set { SetPropertyValue<string>("SubCategory", ref fSubCategory, value); }
        }
        string fStockType;
        [Size(50)]
        public string StockType
        {
            get { return fStockType; }
            set { SetPropertyValue<string>("StockType", ref fStockType, value); }
        }
        string fLocationMain;
        [Size(50)]
        public string LocationMain
        {
            get { return fLocationMain; }
            set { SetPropertyValue<string>("LocationMain", ref fLocationMain, value); }
        }
        string fLocationSecondary;
        [Size(50)]
        public string LocationSecondary
        {
            get { return fLocationSecondary; }
            set { SetPropertyValue<string>("LocationSecondary", ref fLocationSecondary, value); }
        }
        string fBarcode;
        [Size(50)]
        public string Barcode
        {
            get { return fBarcode; }
            set { SetPropertyValue<string>("Barcode", ref fBarcode, value); }
        }
        decimal fMinimumStockLevel;
        public decimal MinimumStockLevel
        {
            get { return fMinimumStockLevel; }
            set { SetPropertyValue<decimal>("MinimumStockLevel", ref fMinimumStockLevel, value); }
        }
        decimal fMaximumStockLevel;
        public decimal MaximumStockLevel
        {
            get { return fMaximumStockLevel; }
            set { SetPropertyValue<decimal>("MaximumStockLevel", ref fMaximumStockLevel, value); }
        }
        decimal fSafetyStock;
        public decimal SafetyStock
        {
            get { return fSafetyStock; }
            set { SetPropertyValue<decimal>("SafetyStock", ref fSafetyStock, value); }
        }
        decimal fWarehousingCost;
        public decimal WarehousingCost
        {
            get { return fWarehousingCost; }
            set { SetPropertyValue<decimal>("WarehousingCost", ref fWarehousingCost, value); }
        }
        string fDiscountCode;
        [Size(50)]
        public string DiscountCode
        {
            get { return fDiscountCode; }
            set { SetPropertyValue<string>("DiscountCode", ref fDiscountCode, value); }
        }
        string fGrouping;
        [Size(50)]
        public string Grouping
        {
            get { return fGrouping; }
            set { SetPropertyValue<string>("Grouping", ref fGrouping, value); }
        }
        double fProfitMargin;
        public double ProfitMargin
        {
            get { return fProfitMargin; }
            set { SetPropertyValue<double>("ProfitMargin", ref fProfitMargin, value); }
        }
        char fLabelFlag;
        public char LabelFlag
        {
            get { return fLabelFlag; }
            set { SetPropertyValue<char>("LabelFlag", ref fLabelFlag, value); }
        }
        bool fRequireSerial;
        public bool RequireSerial
        {
            get { return fRequireSerial; }
            set { SetPropertyValue<bool>("RequireSerial", ref fRequireSerial, value); }
        }
        decimal fSellingPackSize;
        public decimal SellingPackSize
        {
            get { return fSellingPackSize; }
            set { SetPropertyValue<decimal>("SellingPackSize", ref fSellingPackSize, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"ITM_InventoryReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
    }

}
