//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_SYS.SYS_Log")]
    public partial class SYS_Log : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        string fFieldName;
        public string FieldName
        {
            get { return fFieldName; }
            set { SetPropertyValue<string>("FieldName", ref fFieldName, value); }
        }
        string fTableName;
        public string TableName
        {
            get { return fTableName; }
            set { SetPropertyValue<string>("TableName", ref fTableName, value); }
        }
        long fEntityId;
        public long EntityId
        {
            get { return fEntityId; }
            set { SetPropertyValue<long>("EntityId", ref fEntityId, value); }
        }
        string fOldValue;
        [Size(SizeAttribute.Unlimited)]
        public string OldValue
        {
            get { return fOldValue; }
            set { SetPropertyValue<string>("OldValue", ref fOldValue, value); }
        }
        string fNewValue;
        [Size(SizeAttribute.Unlimited)]
        public string NewValue
        {
            get { return fNewValue; }
            set { SetPropertyValue<string>("NewValue", ref fNewValue, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"SYS_LogReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
    }

}
