//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.DataAccessLayer.XPO.Datamodel
{

    [Persistent(@"CDS_SYS.SYS_DOC_Line")]
    public partial class SYS_DOC_Line : XPLiteObject
    {
        long fId;
        [Key(true)]
        public long Id
        {
            get { return fId; }
            set { SetPropertyValue<long>("Id", ref fId, value); }
        }
        SYS_DOC_Header fHeaderId;
        [Association(@"SYS_DOC_LineReferencesSYS_DOC_Header")]
        public SYS_DOC_Header HeaderId
        {
            get { return fHeaderId; }
            set { SetPropertyValue<SYS_DOC_Header>("HeaderId", ref fHeaderId, value); }
        }
        SYS_Entity fItemId;
        [Association(@"SYS_DOC_LineReferencesSYS_Entity")]
        public SYS_Entity ItemId
        {
            get { return fItemId; }
            set { SetPropertyValue<SYS_Entity>("ItemId", ref fItemId, value); }
        }
        int fLineOrder;
        public int LineOrder
        {
            get { return fLineOrder; }
            set { SetPropertyValue<int>("LineOrder", ref fLineOrder, value); }
        }
        decimal fDiscountPercentage;
        public decimal DiscountPercentage
        {
            get { return fDiscountPercentage; }
            set { SetPropertyValue<decimal>("DiscountPercentage", ref fDiscountPercentage, value); }
        }
        decimal fDiscountAmount;
        public decimal DiscountAmount
        {
            get { return fDiscountAmount; }
            set { SetPropertyValue<decimal>("DiscountAmount", ref fDiscountAmount, value); }
        }
        string fDescription;
        [Size(50)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>("Quantity", ref fQuantity, value); }
        }
        decimal fAmount;
        public decimal Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<decimal>("Amount", ref fAmount, value); }
        }
        decimal fTotal;
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>("Total", ref fTotal, value); }
        }
        decimal fTotalTax;
        public decimal TotalTax
        {
            get { return fTotalTax; }
            set { SetPropertyValue<decimal>("TotalTax", ref fTotalTax, value); }
        }
        DateTime fCreatedOn;
        [NonPersistent]
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref fCreatedOn, value); }
        }
        SYS_Person fCreatedBy;
        [Association(@"SYS_DOC_LineReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref fCreatedBy, value); }
        }
        [Association(@"IBO_MovementReferencesSYS_DOC_Line", typeof(IBO_Movement))]
        public XPCollection<IBO_Movement> IBO_Movements { get { return GetCollection<IBO_Movement>("IBO_Movements"); } }
        [Association(@"ITM_MovementReferencesSYS_DOC_Line", typeof(ITM_Movement))]
        public XPCollection<ITM_Movement> ITM_Movements { get { return GetCollection<ITM_Movement>("ITM_Movements"); } }
    }

}
