//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    
    public partial class BalancePivot
    {
        public string PeriodCode { get; set; }
        public Nullable<decimal> BalanceAmount_120 { get; set; }
        public Nullable<decimal> BudgetAmount_120 { get; set; }
        public Nullable<decimal> BalanceAmount_090 { get; set; }
        public Nullable<decimal> BudgetAmount_090 { get; set; }
        public Nullable<decimal> BalanceAmount_060 { get; set; }
        public Nullable<decimal> BudgetAmount_060 { get; set; }
        public Nullable<decimal> BalanceAmount_030 { get; set; }
        public Nullable<decimal> BudgetAmount_030 { get; set; }
        public Nullable<decimal> BalanceAmount_000 { get; set; }
        public Nullable<decimal> BudgetAmount_000 { get; set; }
        public System.DateTime PeriodEndDate { get; set; }
    }
}
