//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    
    public partial class ITM_BOM_Recipe : INotifyPropertyChanged, IBaseEntity
    { 
    	bool hasChanges = false;
        public bool HasChanges
        {
        	get
        	{
                return hasChanges;
        	}
        	set
        	{
                if (hasChanges != value)
                    hasChanges = value;
        	}
        } 
    	
    	bool ignoreChanges = false;
        public bool IgnoreChanges
        {
            get
            {
                
                
                return ignoreChanges;
            }
            set
            {
                if (ignoreChanges != value)
                {
                    ignoreChanges = value;
                }
            }
        }
    
    	List<string> changeList = new List<string>();
    	[Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
        public List<string> ChangeList
        {
            get
            { 
                return changeList;
            }
            set
            {
                if (changeList != value)
                {
                    changeList = value;
                }
            }
        } 
    
    	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged; 
    	private void SetProperty<T>(ref T field, T value, [System.Runtime.CompilerServices.CallerMemberName] string name = "")
    	{
    		if (!EqualityComparer<T>.Default.Equals(field, value))
    		{
    			field = value;
    			//ChangeSet.Add(LogEntry.New<T>(field.ToString(),this.ToString(), this.Id,  field,  value ));
    			var handler = PropertyChanged;
    			if (handler != null)
    			{
    				if(!name.StartsWith("Id") && name != "Title" && name != "CreatedOn" && !IgnoreChanges)  
    				{
    					HasChanges = true;
    					ChangeList.Add(name);
    				}
    
    				handler(this, new System.ComponentModel.PropertyChangedEventArgs(name));
    			}
    		}
    	} 
     
        public ITM_BOM_Recipe()
        {
            this.ITM_BOM_Document = new List<ITM_BOM_Document>();
            this.ITM_BOM_RecipeLine = new List<ITM_BOM_RecipeLine>();
        }
    
        private long id;
        private long itemResultId;
        private string description;
        private decimal quantityResult;
        private Nullable<decimal> building;
        private Nullable<decimal> unBuilding;
        private bool archived;
        private Nullable<System.DateTime> createdOn;
        private Nullable<long> createdBy;
    
        public long Id 
    	{ 
    		get { return id; }
    		set { SetProperty(ref id, value); }
    	 }
        public long ItemResultId 
    	{ 
    		get { return itemResultId; }
    		set { SetProperty(ref itemResultId, value); }
    	 }
        public string Description 
    	{ 
    		get { return description; }
    		set { SetProperty(ref description, value); }
    	 }
        public decimal QuantityResult 
    	{ 
    		get { return quantityResult; }
    		set { SetProperty(ref quantityResult, value); }
    	 }
        public Nullable<decimal> Building 
    	{ 
    		get { return building; }
    		set { SetProperty(ref building, value); }
    	 }
        public Nullable<decimal> UnBuilding 
    	{ 
    		get { return unBuilding; }
    		set { SetProperty(ref unBuilding, value); }
    	 }
        public bool Archived 
    	{ 
    		get { return archived; }
    		set { SetProperty(ref archived, value); }
    	 }
        public Nullable<System.DateTime> CreatedOn 
    	{ 
    		get { return createdOn; }
    		set { SetProperty(ref createdOn, value); }
    	 }
        public Nullable<long> CreatedBy 
    	{ 
    		get { return createdBy; }
    		set { SetProperty(ref createdBy, value); }
    	 }
    
        [System.Xml.Serialization.XmlIgnore]
    	public virtual ICollection<ITM_BOM_Document> ITM_BOM_Document { get; set; }
        [System.Xml.Serialization.XmlIgnore]
    	public virtual ICollection<ITM_BOM_RecipeLine> ITM_BOM_RecipeLine { get; set; }
    }
}
