//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    
    public partial class SYS_DOC_Line : INotifyPropertyChanged, IBaseEntity
    { 
    	bool hasChanges = false;
        public bool HasChanges
        {
        	get
        	{
                return hasChanges;
        	}
        	set
        	{
                if (hasChanges != value)
                    hasChanges = value;
        	}
        } 
    	
    	bool ignoreChanges = false;
        public bool IgnoreChanges
        {
            get
            {
                
                
                return ignoreChanges;
            }
            set
            {
                if (ignoreChanges != value)
                {
                    ignoreChanges = value;
                }
            }
        }
    
    	List<string> changeList = new List<string>();
    	[Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
        public List<string> ChangeList
        {
            get
            { 
                return changeList;
            }
            set
            {
                if (changeList != value)
                {
                    changeList = value;
                }
            }
        } 
    
    	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged; 
    	private void SetProperty<T>(ref T field, T value, [System.Runtime.CompilerServices.CallerMemberName] string name = "")
    	{
    		if (!EqualityComparer<T>.Default.Equals(field, value))
    		{
    			field = value;
    			//ChangeSet.Add(LogEntry.New<T>(field.ToString(),this.ToString(), this.Id,  field,  value ));
    			var handler = PropertyChanged;
    			if (handler != null)
    			{
    				if(!name.StartsWith("Id") && name != "Title" && name != "CreatedOn" && !IgnoreChanges)  
    				{
    					HasChanges = true;
    					ChangeList.Add(name);
    				}
    
    				handler(this, new System.ComponentModel.PropertyChangedEventArgs(name));
    			}
    		}
    	} 
     
        private long id;
        private Nullable<long> headerId;
        private long itemId;
        private int lineOrder;
        private Nullable<decimal> discountPercentage;
        private Nullable<decimal> discountAmount;
        private string description;
        private decimal quantity;
        private decimal amount;
        private decimal total;
        private decimal totalTax;
        private Nullable<System.DateTime> createdOn;
        private Nullable<long> createdBy;
    
        public long Id 
    	{ 
    		get { return id; }
    		set { SetProperty(ref id, value); }
    	 }
        public Nullable<long> HeaderId 
    	{ 
    		get { return headerId; }
    		set { SetProperty(ref headerId, value); }
    	 }
        public long ItemId 
    	{ 
    		get { return itemId; }
    		set { SetProperty(ref itemId, value); }
    	 }
        public int LineOrder 
    	{ 
    		get { return lineOrder; }
    		set { SetProperty(ref lineOrder, value); }
    	 }
        public Nullable<decimal> DiscountPercentage 
    	{ 
    		get { return discountPercentage; }
    		set { SetProperty(ref discountPercentage, value); }
    	 }
        public Nullable<decimal> DiscountAmount 
    	{ 
    		get { return discountAmount; }
    		set { SetProperty(ref discountAmount, value); }
    	 }
        public string Description 
    	{ 
    		get { return description; }
    		set { SetProperty(ref description, value); }
    	 }
        public decimal Quantity 
    	{ 
    		get { return quantity; }
    		set { SetProperty(ref quantity, value); }
    	 }
        public decimal Amount 
    	{ 
    		get { return amount; }
    		set { SetProperty(ref amount, value); }
    	 }
        public decimal Total 
    	{ 
    		get { return total; }
    		set { SetProperty(ref total, value); }
    	 }
        public decimal TotalTax 
    	{ 
    		get { return totalTax; }
    		set { SetProperty(ref totalTax, value); }
    	 }
        public Nullable<System.DateTime> CreatedOn 
    	{ 
    		get { return createdOn; }
    		set { SetProperty(ref createdOn, value); }
    	 }
        public Nullable<long> CreatedBy 
    	{ 
    		get { return createdBy; }
    		set { SetProperty(ref createdBy, value); }
    	 }
    
        
    	public virtual SYS_DOC_Header SYS_DOC_Header { get; set; }
        
    	public virtual SYS_Entity SYS_Entity { get; set; }
        
    	public virtual SYS_Person SYS_Person { get; set; }
    }
}
