//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CompanyHistory
    {
        public long Id { get; set; }
        public long CompanyId { get; set; }
        public string CodeMain { get; set; }
        public string CodeSub { get; set; }
        public string Name { get; set; }
        public Nullable<short> FinancialYear { get; set; }
        public System.DateTime Date { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
