//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MetaStructure
    {
        public long Id { get; set; }
        public long CategoryId { get; set; }
        public string MetaName { get; set; }
        public string CategoryName { get; set; }
        public string Grouping { get; set; }
        public Nullable<bool> Grouped { get; set; }
        public int SortOrder { get; set; }
    }
}
