//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OrderInventoryHistory
    {
        public long Id { get; set; }
        public long EntityId { get; set; }
        public long SupplierId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public byte CostCategoryId { get; set; }
        public decimal TotalOnHand { get; set; }
        public decimal TotalOnOrder { get; set; }
        public decimal TotalOnHold { get; set; }
        public decimal UnitCost { get; set; }
        public decimal UnitAverage { get; set; }
        public string Category { get; set; }
        public string LocationMain { get; set; }
        public decimal MinStockLevel { get; set; }
        public decimal MaxStockLevel { get; set; }
        public decimal MinimumOrderLevel { get; set; }
        public decimal MaximumOrderLevel { get; set; }
        public decimal PackSize { get; set; }
        public decimal WarehousingCost { get; set; }
        public byte OrderLeadTime { get; set; }
        public decimal SafetyStock { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal UnitReplacementCost { get; set; }
        public string StockType { get; set; }
        public decimal d00Month { get; set; }
        public decimal d01Month { get; set; }
        public decimal d02Month { get; set; }
        public decimal d03Month { get; set; }
        public decimal d04Month { get; set; }
        public decimal d05Month { get; set; }
        public decimal d06Month { get; set; }
        public decimal d07Month { get; set; }
        public decimal d08Month { get; set; }
        public decimal d09Month { get; set; }
        public decimal d10Month { get; set; }
        public decimal d11Month { get; set; }
        public decimal d12Month { get; set; }
        public decimal d13Month { get; set; }
        public decimal d14Month { get; set; }
        public decimal d15Month { get; set; }
        public decimal d16Month { get; set; }
        public decimal d17Month { get; set; }
        public decimal d18Month { get; set; }
        public decimal d19Month { get; set; }
        public decimal d20Month { get; set; }
        public decimal d21Month { get; set; }
        public decimal d22Month { get; set; }
        public decimal d23Month { get; set; }
        public decimal d24Month { get; set; }
        public decimal d25Month { get; set; }
        public decimal d26Month { get; set; }
        public decimal d27Month { get; set; }
        public decimal d28Month { get; set; }
        public decimal d29Month { get; set; }
        public decimal d30Month { get; set; }
        public decimal d31Month { get; set; }
        public decimal d32Month { get; set; }
        public decimal d33Month { get; set; }
        public decimal d34Month { get; set; }
        public decimal d35Month { get; set; }
        public decimal d36Month { get; set; }
        public decimal d37Month { get; set; }
        public decimal d38Month { get; set; }
        public decimal d39Month { get; set; }
        public decimal d40Month { get; set; }
        public decimal d41Month { get; set; }
        public decimal d42Month { get; set; }
        public decimal d43Month { get; set; }
        public decimal d44Month { get; set; }
        public decimal d45Month { get; set; }
        public decimal d46Month { get; set; }
        public decimal d47Month { get; set; }
        public decimal d48Month { get; set; }
    }
}
