//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OutstandingOrders
    {
        public Nullable<long> Id { get; set; }
        public long EntityId { get; set; }
        public long TrackId { get; set; }
        public Nullable<long> DocumentNumber { get; set; }
        public string Supplier { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<decimal> Ordered { get; set; }
        public Nullable<decimal> Outstanding { get; set; }
        public long SiteId { get; set; }
    }
}
