//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_StockTakeItem
    {
        public Nullable<long> Id { get; set; }
        public long EntityId { get; set; }
        public long StockTakeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string StockType { get; set; }
        public string LocationMain { get; set; }
        public string LocationSecondary { get; set; }
        public Nullable<decimal> OnHand { get; set; }
    }
}
