//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Site
    {
        public long Id { get; set; }
        public string CodeMain { get; set; }
        public string ShortName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string RegistrationNumber { get; set; }
        public bool Archived { get; set; }
        public string Telephone { get; set; }
        public string VatNumber { get; set; }
        public decimal VatPercentage { get; set; }
        public long BillingAddress { get; set; }
        public long ShippingAddress { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string BankCode { get; set; }
        public string BankAccountNumber { get; set; }
        public string Title { get; set; }
        public long SiteId { get; set; }
    }
}
