//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    [Persistent(@"CDS_ITM.ITM_History")]
    public partial class CDS_ITM_ITM_History : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        CDS_SYS_SYS_Entity _SiteId;
        [Association(@"CDS_ITM_ITM_HistoryReferencesCDS_SYS_SYS_Entity1")]
        public CDS_SYS_SYS_Entity SiteId
        {
            get { return _SiteId; }
            set { SetPropertyValue<CDS_SYS_SYS_Entity>("SiteId", ref _SiteId, value); }
        }
        CDS_SYS_SYS_Entity _InventoryId;
        [Association(@"CDS_ITM_ITM_HistoryReferencesCDS_SYS_SYS_Entity")]
        public CDS_SYS_SYS_Entity InventoryId
        {
            get { return _InventoryId; }
            set { SetPropertyValue<CDS_SYS_SYS_Entity>("InventoryId", ref _InventoryId, value); }
        }
        CDS_SYS_SYS_Period _PeriodId;
        [Association(@"CDS_ITM_ITM_HistoryReferencesCDS_SYS_SYS_Period")]
        public CDS_SYS_SYS_Period PeriodId
        {
            get { return _PeriodId; }
            set { SetPropertyValue<CDS_SYS_SYS_Period>("PeriodId", ref _PeriodId, value); }
        }
        decimal _Amount;
        public decimal Amount
        {
            get { return _Amount; }
            set { SetPropertyValue<decimal>("Amount", ref _Amount, value); }
        }
        decimal _Movement;
        public decimal Movement
        {
            get { return _Movement; }
            set { SetPropertyValue<decimal>("Movement", ref _Movement, value); }
        }
        decimal _OnHand;
        public decimal OnHand
        {
            get { return _OnHand; }
            set { SetPropertyValue<decimal>("OnHand", ref _OnHand, value); }
        }
        decimal _OnHold;
        public decimal OnHold
        {
            get { return _OnHold; }
            set { SetPropertyValue<decimal>("OnHold", ref _OnHold, value); }
        }
        decimal _OnReserve;
        public decimal OnReserve
        {
            get { return _OnReserve; }
            set { SetPropertyValue<decimal>("OnReserve", ref _OnReserve, value); }
        }
        decimal _OnOrder;
        public decimal OnOrder
        {
            get { return _OnOrder; }
            set { SetPropertyValue<decimal>("OnOrder", ref _OnOrder, value); }
        }
        decimal _UnitPrice;
        public decimal UnitPrice
        {
            get { return _UnitPrice; }
            set { SetPropertyValue<decimal>("UnitPrice", ref _UnitPrice, value); }
        }
        decimal _UnitCost;
        public decimal UnitCost
        {
            get { return _UnitCost; }
            set { SetPropertyValue<decimal>("UnitCost", ref _UnitCost, value); }
        }
        decimal _UnitAverage;
        public decimal UnitAverage
        {
            get { return _UnitAverage; }
            set { SetPropertyValue<decimal>("UnitAverage", ref _UnitAverage, value); }
        }
        DateTime _FirstSold;
        public DateTime FirstSold
        {
            get { return _FirstSold; }
            set { SetPropertyValue<DateTime>("FirstSold", ref _FirstSold, value); }
        }
        DateTime _FirstPurchased;
        public DateTime FirstPurchased
        {
            get { return _FirstPurchased; }
            set { SetPropertyValue<DateTime>("FirstPurchased", ref _FirstPurchased, value); }
        }
        DateTime _LastSold;
        public DateTime LastSold
        {
            get { return _LastSold; }
            set { SetPropertyValue<DateTime>("LastSold", ref _LastSold, value); }
        }
        DateTime _LastPurchased;
        public DateTime LastPurchased
        {
            get { return _LastPurchased; }
            set { SetPropertyValue<DateTime>("LastPurchased", ref _LastPurchased, value); }
        }
        DateTime _LastMovement;
        public DateTime LastMovement
        {
            get { return _LastMovement; }
            set { SetPropertyValue<DateTime>("LastMovement", ref _LastMovement, value); }
        }
        decimal _Sales12;
        public decimal Sales12
        {
            get { return _Sales12; }
            set { SetPropertyValue<decimal>("Sales12", ref _Sales12, value); }
        }
        decimal _Sales6;
        public decimal Sales6
        {
            get { return _Sales6; }
            set { SetPropertyValue<decimal>("Sales6", ref _Sales6, value); }
        }
        decimal _Sales3;
        public decimal Sales3
        {
            get { return _Sales3; }
            set { SetPropertyValue<decimal>("Sales3", ref _Sales3, value); }
        }
    }

}
