//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    [Persistent(@"CDS_AOR.AOR_OrderLine")]
    public partial class CDS_AOR_AOR_OrderLine : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        CDS_AOR_AOR_Order _OrderId;
        [Association(@"CDS_AOR_AOR_OrderLineReferencesCDS_AOR_AOR_Order")]
        public CDS_AOR_AOR_Order OrderId
        {
            get { return _OrderId; }
            set { SetPropertyValue<CDS_AOR_AOR_Order>("OrderId", ref _OrderId, value); }
        }
        CDS_SYS_SYS_Entity _SupplierId;
        [Association(@"CDS_AOR_AOR_OrderLineReferencesCDS_SYS_SYS_Entity1")]
        public CDS_SYS_SYS_Entity SupplierId
        {
            get { return _SupplierId; }
            set { SetPropertyValue<CDS_SYS_SYS_Entity>("SupplierId", ref _SupplierId, value); }
        }
        CDS_SYS_SYS_Entity _InventoryId;
        [Association(@"CDS_AOR_AOR_OrderLineReferencesCDS_SYS_SYS_Entity")]
        public CDS_SYS_SYS_Entity InventoryId
        {
            get { return _InventoryId; }
            set { SetPropertyValue<CDS_SYS_SYS_Entity>("InventoryId", ref _InventoryId, value); }
        }
        string _Site;
        [Size(50)]
        public string Site
        {
            get { return _Site; }
            set { SetPropertyValue<string>("Site", ref _Site, value); }
        }
        string _Supplier;
        [Size(50)]
        public string Supplier
        {
            get { return _Supplier; }
            set { SetPropertyValue<string>("Supplier", ref _Supplier, value); }
        }
        string _ShortName;
        [Size(50)]
        public string ShortName
        {
            get { return _ShortName; }
            set { SetPropertyValue<string>("ShortName", ref _ShortName, value); }
        }
        string _Name;
        [Size(50)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        decimal _SafetyStock;
        public decimal SafetyStock
        {
            get { return _SafetyStock; }
            set { SetPropertyValue<decimal>("SafetyStock", ref _SafetyStock, value); }
        }
        decimal _OnHand;
        public decimal OnHand
        {
            get { return _OnHand; }
            set { SetPropertyValue<decimal>("OnHand", ref _OnHand, value); }
        }
        decimal _OnHold;
        public decimal OnHold
        {
            get { return _OnHold; }
            set { SetPropertyValue<decimal>("OnHold", ref _OnHold, value); }
        }
        decimal _OnReserve;
        public decimal OnReserve
        {
            get { return _OnReserve; }
            set { SetPropertyValue<decimal>("OnReserve", ref _OnReserve, value); }
        }
        decimal _OnOrder;
        public decimal OnOrder
        {
            get { return _OnOrder; }
            set { SetPropertyValue<decimal>("OnOrder", ref _OnOrder, value); }
        }
        decimal _UnitCost;
        public decimal UnitCost
        {
            get { return _UnitCost; }
            set { SetPropertyValue<decimal>("UnitCost", ref _UnitCost, value); }
        }
        decimal _UnitAverage;
        public decimal UnitAverage
        {
            get { return _UnitAverage; }
            set { SetPropertyValue<decimal>("UnitAverage", ref _UnitAverage, value); }
        }
        decimal _UnitPrice;
        public decimal UnitPrice
        {
            get { return _UnitPrice; }
            set { SetPropertyValue<decimal>("UnitPrice", ref _UnitPrice, value); }
        }
        decimal _AvgDemand;
        public decimal AvgDemand
        {
            get { return _AvgDemand; }
            set { SetPropertyValue<decimal>("AvgDemand", ref _AvgDemand, value); }
        }
        decimal _Eoq;
        public decimal Eoq
        {
            get { return _Eoq; }
            set { SetPropertyValue<decimal>("Eoq", ref _Eoq, value); }
        }
        decimal _OrderPoint;
        public decimal OrderPoint
        {
            get { return _OrderPoint; }
            set { SetPropertyValue<decimal>("OrderPoint", ref _OrderPoint, value); }
        }
        decimal _OrderAmountCalculated;
        public decimal OrderAmountCalculated
        {
            get { return _OrderAmountCalculated; }
            set { SetPropertyValue<decimal>("OrderAmountCalculated", ref _OrderAmountCalculated, value); }
        }
        decimal _OrderAmount;
        public decimal OrderAmount
        {
            get { return _OrderAmount; }
            set { SetPropertyValue<decimal>("OrderAmount", ref _OrderAmount, value); }
        }
        decimal _Total;
        public decimal Total
        {
            get { return _Total; }
            set { SetPropertyValue<decimal>("Total", ref _Total, value); }
        }
        decimal _TotalTax;
        public decimal TotalTax
        {
            get { return _TotalTax; }
            set { SetPropertyValue<decimal>("TotalTax", ref _TotalTax, value); }
        }
        CDS_SYS_SYS_Person _CreatedBy;
        [Association(@"CDS_AOR_AOR_OrderLineReferencesCDS_SYS_SYS_Person")]
        public CDS_SYS_SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<CDS_SYS_SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
    }

}
