//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    [Persistent(@"CDS_ITM.ITM_DIS_Discount")]
    public partial class CDS_ITM_ITM_DIS_Discount : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        CDS_SYS_SYS_Entity _InventoryId;
        [Association(@"CDS_ITM_ITM_DIS_DiscountReferencesCDS_SYS_SYS_Entity")]
        public CDS_SYS_SYS_Entity InventoryId
        {
            get { return _InventoryId; }
            set { SetPropertyValue<CDS_SYS_SYS_Entity>("InventoryId", ref _InventoryId, value); }
        }
        CDS_SYS_SYS_Entity _EntityId;
        [Association(@"CDS_ITM_ITM_DIS_DiscountReferencesCDS_SYS_SYS_Entity1")]
        public CDS_SYS_SYS_Entity EntityId
        {
            get { return _EntityId; }
            set { SetPropertyValue<CDS_SYS_SYS_Entity>("EntityId", ref _EntityId, value); }
        }
        CDS_ITM_ITM_DIS_Type _DiscountTypeId;
        [Association(@"CDS_ITM_ITM_DIS_DiscountReferencesCDS_ITM_ITM_DIS_Type")]
        public CDS_ITM_ITM_DIS_Type DiscountTypeId
        {
            get { return _DiscountTypeId; }
            set { SetPropertyValue<CDS_ITM_ITM_DIS_Type>("DiscountTypeId", ref _DiscountTypeId, value); }
        }
        CDS_ITM_ITM_DIS_AmountType _DiscountAmountTypeId;
        [Association(@"CDS_ITM_ITM_DIS_DiscountReferencesCDS_ITM_ITM_DIS_AmountType")]
        public CDS_ITM_ITM_DIS_AmountType DiscountAmountTypeId
        {
            get { return _DiscountAmountTypeId; }
            set { SetPropertyValue<CDS_ITM_ITM_DIS_AmountType>("DiscountAmountTypeId", ref _DiscountAmountTypeId, value); }
        }
        string _CompanyDiscountCode;
        [Size(50)]
        public string CompanyDiscountCode
        {
            get { return _CompanyDiscountCode; }
            set { SetPropertyValue<string>("CompanyDiscountCode", ref _CompanyDiscountCode, value); }
        }
        string _InventoryDiscountCode;
        [Size(50)]
        public string InventoryDiscountCode
        {
            get { return _InventoryDiscountCode; }
            set { SetPropertyValue<string>("InventoryDiscountCode", ref _InventoryDiscountCode, value); }
        }
        decimal _VolumeNumber;
        public decimal VolumeNumber
        {
            get { return _VolumeNumber; }
            set { SetPropertyValue<decimal>("VolumeNumber", ref _VolumeNumber, value); }
        }
        bool _PriorityDiscount;
        public bool PriorityDiscount
        {
            get { return _PriorityDiscount; }
            set { SetPropertyValue<bool>("PriorityDiscount", ref _PriorityDiscount, value); }
        }
        decimal _CompanyDiscount;
        public decimal CompanyDiscount
        {
            get { return _CompanyDiscount; }
            set { SetPropertyValue<decimal>("CompanyDiscount", ref _CompanyDiscount, value); }
        }
        decimal _WorkshopDiscount;
        public decimal WorkshopDiscount
        {
            get { return _WorkshopDiscount; }
            set { SetPropertyValue<decimal>("WorkshopDiscount", ref _WorkshopDiscount, value); }
        }
        decimal _VolumeDiscount;
        public decimal VolumeDiscount
        {
            get { return _VolumeDiscount; }
            set { SetPropertyValue<decimal>("VolumeDiscount", ref _VolumeDiscount, value); }
        }
        DateTime _StartDate;
        public DateTime StartDate
        {
            get { return _StartDate; }
            set { SetPropertyValue<DateTime>("StartDate", ref _StartDate, value); }
        }
        DateTime _EndDate;
        public DateTime EndDate
        {
            get { return _EndDate; }
            set { SetPropertyValue<DateTime>("EndDate", ref _EndDate, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        CDS_SYS_SYS_Person _CreatedBy;
        [Association(@"CDS_ITM_ITM_DIS_DiscountReferencesCDS_SYS_SYS_Person")]
        public CDS_SYS_SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<CDS_SYS_SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
    }

}
