//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class GLX_Account : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        SYS_Entity _EntityId;
        [Association(@"GLX_AccountReferencesSYS_Entity")]
        public SYS_Entity EntityId
        {
            get { return _EntityId; }
            set { SetPropertyValue<SYS_Entity>("EntityId", ref _EntityId, value); }
        }
        GLX_Type _AccountTypeId;
        [Association(@"GLX_AccountReferencesGLX_Type")]
        public GLX_Type AccountTypeId
        {
            get { return _AccountTypeId; }
            set { SetPropertyValue<GLX_Type>("AccountTypeId", ref _AccountTypeId, value); }
        }
        SYS_Entity _CenterId;
        [Association(@"GLX_AccountReferencesSYS_Entity1")]
        public SYS_Entity CenterId
        {
            get { return _CenterId; }
            set { SetPropertyValue<SYS_Entity>("CenterId", ref _CenterId, value); }
        }
        bool _AgingAccount;
        public bool AgingAccount
        {
            get { return _AgingAccount; }
            set { SetPropertyValue<bool>("AgingAccount", ref _AgingAccount, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        SYS_Person _CreatedBy;
        [Association(@"GLX_AccountReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
        SYS_Entity _ControlId;
        [Association(@"GLX_AccountReferencesSYS_Entity2")]
        public SYS_Entity ControlId
        {
            get { return _ControlId; }
            set { SetPropertyValue<SYS_Entity>("ControlId", ref _ControlId, value); }
        }
        SYS_Entity _MasterControlId;
        [Association(@"GLX_AccountReferencesSYS_Entity3")]
        public SYS_Entity MasterControlId
        {
            get { return _MasterControlId; }
            set { SetPropertyValue<SYS_Entity>("MasterControlId", ref _MasterControlId, value); }
        }
        string _BalanceGroup;
        [Size(10)]
        public string BalanceGroup
        {
            get { return _BalanceGroup; }
            set { SetPropertyValue<string>("BalanceGroup", ref _BalanceGroup, value); }
        }
        SYS_Entity _SiteId;
        [Association(@"GLX_AccountReferencesSYS_Entity4")]
        public SYS_Entity SiteId
        {
            get { return _SiteId; }
            set { SetPropertyValue<SYS_Entity>("SiteId", ref _SiteId, value); }
        }
    }

}
