//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class GLX_SystemAccountType : XPLiteObject
    {
        int _Id;
        [Key(true)]
        public int Id
        {
            get { return _Id; }
            set { SetPropertyValue<int>("Id", ref _Id, value); }
        }
        string _Name;
        [Size(50)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        GLX_Type _TypeId;
        [Association(@"GLX_SystemAccountTypeReferencesGLX_Type")]
        public GLX_Type TypeId
        {
            get { return _TypeId; }
            set { SetPropertyValue<GLX_Type>("TypeId", ref _TypeId, value); }
        }
        [Association(@"GLX_SiteAccountReferencesGLX_SystemAccountType", typeof(GLX_SiteAccount))]
        public XPCollection<GLX_SiteAccount> GLX_SiteAccounts { get { return GetCollection<GLX_SiteAccount>("GLX_SiteAccounts"); } }
    }

}
