//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class GLX_SiteAccount : XPLiteObject
    {
        int _Id;
        [Key(true)]
        public int Id
        {
            get { return _Id; }
            set { SetPropertyValue<int>("Id", ref _Id, value); }
        }
        SYS_Entity _EntityId;
        [Association(@"GLX_SiteAccountReferencesSYS_Entity")]
        public SYS_Entity EntityId
        {
            get { return _EntityId; }
            set { SetPropertyValue<SYS_Entity>("EntityId", ref _EntityId, value); }
        }
        GLX_SystemAccountType _TypeId;
        [Association(@"GLX_SiteAccountReferencesGLX_SystemAccountType")]
        public GLX_SystemAccountType TypeId
        {
            get { return _TypeId; }
            set { SetPropertyValue<GLX_SystemAccountType>("TypeId", ref _TypeId, value); }
        }
        bool _SystemDefaultAccount;
        public bool SystemDefaultAccount
        {
            get { return _SystemDefaultAccount; }
            set { SetPropertyValue<bool>("SystemDefaultAccount", ref _SystemDefaultAccount, value); }
        }
        string _ShortDescription;
        [Size(20)]
        public string ShortDescription
        {
            get { return _ShortDescription; }
            set { SetPropertyValue<string>("ShortDescription", ref _ShortDescription, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        SYS_Person _CreatedBy;
        [Association(@"GLX_SiteAccountReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
    }

}
