//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class IBO_TRX_Header : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        SYS_Entity _EntityId;
        [Association(@"IBO_TRX_HeaderReferencesSYS_Entity")]
        public SYS_Entity EntityId
        {
            get { return _EntityId; }
            set { SetPropertyValue<SYS_Entity>("EntityId", ref _EntityId, value); }
        }
        ORG_Company _CustomerId;
        [Association(@"IBO_TRX_HeaderReferencesORG_Company")]
        public ORG_Company CustomerId
        {
            get { return _CustomerId; }
            set { SetPropertyValue<ORG_Company>("CustomerId", ref _CustomerId, value); }
        }
        ORG_Company _SupplierId;
        [Association(@"IBO_TRX_HeaderReferencesORG_Company1")]
        public ORG_Company SupplierId
        {
            get { return _SupplierId; }
            set { SetPropertyValue<ORG_Company>("SupplierId", ref _SupplierId, value); }
        }
        string _Supplier;
        [Size(200)]
        public string Supplier
        {
            get { return _Supplier; }
            set { SetPropertyValue<string>("Supplier", ref _Supplier, value); }
        }
        string _Customer;
        [Size(200)]
        public string Customer
        {
            get { return _Customer; }
            set { SetPropertyValue<string>("Customer", ref _Customer, value); }
        }
        decimal _Quantity;
        public decimal Quantity
        {
            get { return _Quantity; }
            set { SetPropertyValue<decimal>("Quantity", ref _Quantity, value); }
        }
        decimal _UnitCost;
        public decimal UnitCost
        {
            get { return _UnitCost; }
            set { SetPropertyValue<decimal>("UnitCost", ref _UnitCost, value); }
        }
        decimal _UnitPrice;
        public decimal UnitPrice
        {
            get { return _UnitPrice; }
            set { SetPropertyValue<decimal>("UnitPrice", ref _UnitPrice, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        SYS_Person _CreatedBy;
        [Association(@"IBO_TRX_HeaderReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
    }

}
