//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class RPT_Report : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        string _Code;
        [Size(50)]
        public string Code
        {
            get { return _Code; }
            set { SetPropertyValue<string>("Code", ref _Code, value); }
        }
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _Description;
        [Size(2000)]
        public string Description
        {
            get { return _Description; }
            set { SetPropertyValue<string>("Description", ref _Description, value); }
        }
        string _Category;
        [Size(50)]
        public string Category
        {
            get { return _Category; }
            set { SetPropertyValue<string>("Category", ref _Category, value); }
        }
        string _SubCategory;
        [Size(50)]
        public string SubCategory
        {
            get { return _SubCategory; }
            set { SetPropertyValue<string>("SubCategory", ref _SubCategory, value); }
        }
        string _Data;
        [Size(SizeAttribute.Unlimited)]
        public string Data
        {
            get { return _Data; }
            set { SetPropertyValue<string>("Data", ref _Data, value); }
        }
        bool _Archived;
        public bool Archived
        {
            get { return _Archived; }
            set { SetPropertyValue<bool>("Archived", ref _Archived, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        SYS_Person _CreatedBy;
        [Association(@"RPT_ReportReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
        int _SecurityLevel;
        public int SecurityLevel
        {
            get { return _SecurityLevel; }
            set { SetPropertyValue<int>("SecurityLevel", ref _SecurityLevel, value); }
        }
    }

}
