//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class SYS_Printer : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        string _Name;
        [Size(50)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _Location;
        [Size(50)]
        public string Location
        {
            get { return _Location; }
            set { SetPropertyValue<string>("Location", ref _Location, value); }
        }
        string _PrinterType;
        [Size(200)]
        public string PrinterType
        {
            get { return _PrinterType; }
            set { SetPropertyValue<string>("PrinterType", ref _PrinterType, value); }
        }
        string _PrinterModel;
        [Size(200)]
        public string PrinterModel
        {
            get { return _PrinterModel; }
            set { SetPropertyValue<string>("PrinterModel", ref _PrinterModel, value); }
        }
        bool _Archived;
        public bool Archived
        {
            get { return _Archived; }
            set { SetPropertyValue<bool>("Archived", ref _Archived, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        SYS_Person _CreatedBy;
        [Association(@"SYS_PrinterReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
        [Association(@"SEC_UserReferencesSYS_Printer", typeof(SEC_User))]
        public XPCollection<SEC_User> SEC_Users { get { return GetCollection<SEC_User>("SEC_Users"); } }
        [Association(@"SYS_SiteReferencesSYS_Printer", typeof(SYS_Site))]
        public XPCollection<SYS_Site> SYS_Sites { get { return GetCollection<SYS_Site>("SYS_Sites"); } }
        [Association(@"SYS_SiteReferencesSYS_Printer1", typeof(SYS_Site))]
        public XPCollection<SYS_Site> SYS_Sites1 { get { return GetCollection<SYS_Site>("SYS_Sites1"); } }
        [Association(@"SYS_SiteReferencesSYS_Printer2", typeof(SYS_Site))]
        public XPCollection<SYS_Site> SYS_Sites2 { get { return GetCollection<SYS_Site>("SYS_Sites2"); } }
    }

}
