//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class CAT_Category : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        CAT_Category _CategoryId;
        [Association(@"CAT_CategoryReferencesCAT_Category")]
        public CAT_Category CategoryId
        {
            get { return _CategoryId; }
            set { SetPropertyValue<CAT_Category>("CategoryId", ref _CategoryId, value); }
        }
        CAT_Catalogue _CatalogueId;
        [Association(@"CAT_CategoryReferencesCAT_Catalogue")]
        public CAT_Catalogue CatalogueId
        {
            get { return _CatalogueId; }
            set { SetPropertyValue<CAT_Catalogue>("CatalogueId", ref _CatalogueId, value); }
        }
        string _Name;
        [Size(200)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        SYS_Person _CreatedBy;
        [Association(@"CAT_CategoryReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
        [Association(@"CAT_ItemDataReferencesCAT_Category", typeof(CAT_ItemData))]
        public XPCollection<CAT_ItemData> CAT_ItemDatas { get { return GetCollection<CAT_ItemData>("CAT_ItemDatas"); } }
        [Association(@"CAT_MetaDataReferencesCAT_Category", typeof(CAT_MetaData))]
        public XPCollection<CAT_MetaData> CAT_MetaDatas { get { return GetCollection<CAT_MetaData>("CAT_MetaDatas"); } }
        [Association(@"CAT_CategoryReferencesCAT_Category", typeof(CAT_Category))]
        public XPCollection<CAT_Category> CAT_CategoryCollection { get { return GetCollection<CAT_Category>("CAT_CategoryCollection"); } }
        [Association(@"CAT_MetaReferencesCAT_Category", typeof(CAT_Meta))]
        public XPCollection<CAT_Meta> CAT_Metas { get { return GetCollection<CAT_Meta>("CAT_Metas"); } }
    }

}
