//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    [Persistent(@"CDS_ORG.ORG_Company")]
    public partial class CDS_ORG_ORG_Company : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        CDS_SYS_SYS_Site _SiteId;
        [Association(@"CDS_ORG_ORG_CompanyReferencesCDS_SYS_SYS_Site")]
        public CDS_SYS_SYS_Site SiteId
        {
            get { return _SiteId; }
            set { SetPropertyValue<CDS_SYS_SYS_Site>("SiteId", ref _SiteId, value); }
        }
        CDS_ORG_ORG_Entity _EntityId;
        [Association(@"CDS_ORG_ORG_CompanyReferencesCDS_ORG_ORG_Entity")]
        public CDS_ORG_ORG_Entity EntityId
        {
            get { return _EntityId; }
            set { SetPropertyValue<CDS_ORG_ORG_Entity>("EntityId", ref _EntityId, value); }
        }
        CDS_ORG_ORG_Type _TypeId;
        [Association(@"CDS_ORG_ORG_CompanyReferencesCDS_ORG_ORG_Type")]
        public CDS_ORG_ORG_Type TypeId
        {
            get { return _TypeId; }
            set { SetPropertyValue<CDS_ORG_ORG_Type>("TypeId", ref _TypeId, value); }
        }
        CDS_ORG_ORG_PaymentTerm _PaymentTermId;
        [Association(@"CDS_ORG_ORG_CompanyReferencesCDS_ORG_ORG_PaymentTerm")]
        public CDS_ORG_ORG_PaymentTerm PaymentTermId
        {
            get { return _PaymentTermId; }
            set { SetPropertyValue<CDS_ORG_ORG_PaymentTerm>("PaymentTermId", ref _PaymentTermId, value); }
        }
        CDS_ORG_ORG_CostCategory _CostCategoryId;
        [Association(@"CDS_ORG_ORG_CompanyReferencesCDS_ORG_ORG_CostCategory")]
        public CDS_ORG_ORG_CostCategory CostCategoryId
        {
            get { return _CostCategoryId; }
            set { SetPropertyValue<CDS_ORG_ORG_CostCategory>("CostCategoryId", ref _CostCategoryId, value); }
        }
        CDS_SYS_SYS_Entity _AccountId;
        [Association(@"CDS_ORG_ORG_CompanyReferencesCDS_SYS_SYS_Entity")]
        public CDS_SYS_SYS_Entity AccountId
        {
            get { return _AccountId; }
            set { SetPropertyValue<CDS_SYS_SYS_Entity>("AccountId", ref _AccountId, value); }
        }
        string _Prefix;
        [Size(50)]
        public string Prefix
        {
            get { return _Prefix; }
            set { SetPropertyValue<string>("Prefix", ref _Prefix, value); }
        }
        bool _OpenItem;
        public bool OpenItem
        {
            get { return _OpenItem; }
            set { SetPropertyValue<bool>("OpenItem", ref _OpenItem, value); }
        }
        bool _Active;
        public bool Active
        {
            get { return _Active; }
            set { SetPropertyValue<bool>("Active", ref _Active, value); }
        }
        bool _OverrideAccount;
        public bool OverrideAccount
        {
            get { return _OverrideAccount; }
            set { SetPropertyValue<bool>("OverrideAccount", ref _OverrideAccount, value); }
        }
        decimal _AccountLimit;
        public decimal AccountLimit
        {
            get { return _AccountLimit; }
            set { SetPropertyValue<decimal>("AccountLimit", ref _AccountLimit, value); }
        }
        string _DiscountCode;
        [Size(20)]
        public string DiscountCode
        {
            get { return _DiscountCode; }
            set { SetPropertyValue<string>("DiscountCode", ref _DiscountCode, value); }
        }
        string _TagCode;
        [Size(20)]
        public string TagCode
        {
            get { return _TagCode; }
            set { SetPropertyValue<string>("TagCode", ref _TagCode, value); }
        }
        string _AreaCode;
        [Size(20)]
        public string AreaCode
        {
            get { return _AreaCode; }
            set { SetPropertyValue<string>("AreaCode", ref _AreaCode, value); }
        }
        string _RepCode;
        [Size(20)]
        public string RepCode
        {
            get { return _RepCode; }
            set { SetPropertyValue<string>("RepCode", ref _RepCode, value); }
        }
        string _SalesmanCode;
        [Size(20)]
        public string SalesmanCode
        {
            get { return _SalesmanCode; }
            set { SetPropertyValue<string>("SalesmanCode", ref _SalesmanCode, value); }
        }
        string _StatementPreference;
        [Size(20)]
        public string StatementPreference
        {
            get { return _StatementPreference; }
            set { SetPropertyValue<string>("StatementPreference", ref _StatementPreference, value); }
        }
        string _CountryCode;
        [Size(20)]
        public string CountryCode
        {
            get { return _CountryCode; }
            set { SetPropertyValue<string>("CountryCode", ref _CountryCode, value); }
        }
        string _URL;
        [Size(50)]
        public string URL
        {
            get { return _URL; }
            set { SetPropertyValue<string>("URL", ref _URL, value); }
        }
        string _Username;
        [Size(50)]
        public string Username
        {
            get { return _Username; }
            set { SetPropertyValue<string>("Username", ref _Username, value); }
        }
        string _Password;
        [Size(50)]
        public string Password
        {
            get { return _Password; }
            set { SetPropertyValue<string>("Password", ref _Password, value); }
        }
        string _CustomValue1;
        [Size(50)]
        public string CustomValue1
        {
            get { return _CustomValue1; }
            set { SetPropertyValue<string>("CustomValue1", ref _CustomValue1, value); }
        }
        string _CustomValue2;
        [Size(50)]
        public string CustomValue2
        {
            get { return _CustomValue2; }
            set { SetPropertyValue<string>("CustomValue2", ref _CustomValue2, value); }
        }
        string _CustomValue3;
        [Size(50)]
        public string CustomValue3
        {
            get { return _CustomValue3; }
            set { SetPropertyValue<string>("CustomValue3", ref _CustomValue3, value); }
        }
        string _CustomValue4;
        [Size(50)]
        public string CustomValue4
        {
            get { return _CustomValue4; }
            set { SetPropertyValue<string>("CustomValue4", ref _CustomValue4, value); }
        }
        string _CustomValue5;
        [Size(50)]
        public string CustomValue5
        {
            get { return _CustomValue5; }
            set { SetPropertyValue<string>("CustomValue5", ref _CustomValue5, value); }
        }
        string _CustomValue6;
        [Size(50)]
        public string CustomValue6
        {
            get { return _CustomValue6; }
            set { SetPropertyValue<string>("CustomValue6", ref _CustomValue6, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        CDS_SYS_SYS_Person _CreatedBy;
        [Association(@"CDS_ORG_ORG_CompanyReferencesCDS_SYS_SYS_Person")]
        public CDS_SYS_SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<CDS_SYS_SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
        [Association(@"CDS_SYS_SYS_SiteReferencesCDS_ORG_ORG_Company", typeof(CDS_SYS_SYS_Site))]
        public XPCollection<CDS_SYS_SYS_Site> CDS_SYS_SYS_Sites { get { return GetCollection<CDS_SYS_SYS_Site>("CDS_SYS_SYS_Sites"); } }
        [Association(@"CDS_IBO_IBO_TRX_HeaderReferencesCDS_ORG_ORG_Company", typeof(CDS_IBO_IBO_TRX_Header))]
        public XPCollection<CDS_IBO_IBO_TRX_Header> CDS_IBO_IBO_TRX_Headers { get { return GetCollection<CDS_IBO_IBO_TRX_Header>("CDS_IBO_IBO_TRX_Headers"); } }
        [Association(@"CDS_IBO_IBO_TRX_HeaderReferencesCDS_ORG_ORG_Company1", typeof(CDS_IBO_IBO_TRX_Header))]
        public XPCollection<CDS_IBO_IBO_TRX_Header> CDS_IBO_IBO_TRX_Headers1 { get { return GetCollection<CDS_IBO_IBO_TRX_Header>("CDS_IBO_IBO_TRX_Headers1"); } }
        [Association(@"CDS_JOB_JOB_HeaderReferencesCDS_ORG_ORG_Company", typeof(CDS_JOB_JOB_Header))]
        public XPCollection<CDS_JOB_JOB_Header> CDS_JOB_JOB_Headers { get { return GetCollection<CDS_JOB_JOB_Header>("CDS_JOB_JOB_Headers"); } }
        [Association(@"CDS_ORG_ORG_CompanyAddressReferencesCDS_ORG_ORG_Company", typeof(CDS_ORG_ORG_CompanyAddress))]
        public XPCollection<CDS_ORG_ORG_CompanyAddress> CDS_ORG_ORG_CompanyAddresss { get { return GetCollection<CDS_ORG_ORG_CompanyAddress>("CDS_ORG_ORG_CompanyAddresss"); } }
        [Association(@"CDS_ORG_ORG_DistributionReferencesCDS_ORG_ORG_Company", typeof(CDS_ORG_ORG_Distribution))]
        public XPCollection<CDS_ORG_ORG_Distribution> CDS_ORG_ORG_Distributions { get { return GetCollection<CDS_ORG_ORG_Distribution>("CDS_ORG_ORG_Distributions"); } }
        [Association(@"CDS_ORG_ORG_HistoryReferencesCDS_ORG_ORG_Company", typeof(CDS_ORG_ORG_History))]
        public XPCollection<CDS_ORG_ORG_History> CDS_ORG_ORG_Historys { get { return GetCollection<CDS_ORG_ORG_History>("CDS_ORG_ORG_Historys"); } }
        [Association(@"CDS_ORG_ORG_TRX_HeaderReferencesCDS_ORG_ORG_Company", typeof(CDS_ORG_ORG_TRX_Header))]
        public XPCollection<CDS_ORG_ORG_TRX_Header> CDS_ORG_ORG_TRX_Headers { get { return GetCollection<CDS_ORG_ORG_TRX_Header>("CDS_ORG_ORG_TRX_Headers"); } }
        [Association(@"CDS_ORG_ORG_TRX_LostSaleReferencesCDS_ORG_ORG_Company", typeof(CDS_ORG_ORG_TRX_LostSale))]
        public XPCollection<CDS_ORG_ORG_TRX_LostSale> CDS_ORG_ORG_TRX_LostSales { get { return GetCollection<CDS_ORG_ORG_TRX_LostSale>("CDS_ORG_ORG_TRX_LostSales"); } }
    }

}
