//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    [Persistent(@"CDS_ITM.ITM_Kit")]
    public partial class CDS_ITM_ITM_Kit : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        CDS_SYS_SYS_Entity _ParentItemId;
        [Association(@"CDS_ITM_ITM_KitReferencesCDS_SYS_SYS_Entity1")]
        public CDS_SYS_SYS_Entity ParentItemId
        {
            get { return _ParentItemId; }
            set { SetPropertyValue<CDS_SYS_SYS_Entity>("ParentItemId", ref _ParentItemId, value); }
        }
        CDS_SYS_SYS_Entity _ChildItemId;
        [Association(@"CDS_ITM_ITM_KitReferencesCDS_SYS_SYS_Entity")]
        public CDS_SYS_SYS_Entity ChildItemId
        {
            get { return _ChildItemId; }
            set { SetPropertyValue<CDS_SYS_SYS_Entity>("ChildItemId", ref _ChildItemId, value); }
        }
        string _Description;
        [Size(1000)]
        public string Description
        {
            get { return _Description; }
            set { SetPropertyValue<string>("Description", ref _Description, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        CDS_SYS_SYS_Person _CreatedBy;
        [Association(@"CDS_ITM_ITM_KitReferencesCDS_SYS_SYS_Person")]
        public CDS_SYS_SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<CDS_SYS_SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
    }

}
