//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    [Persistent(@"CDS_ITM.ITM_BOM_RecipeLine")]
    public partial class CDS_ITM_ITM_BOM_RecipeLine : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        CDS_ITM_ITM_BOM_Recipe _RecipeId;
        [Association(@"CDS_ITM_ITM_BOM_RecipeLineReferencesCDS_ITM_ITM_BOM_Recipe")]
        public CDS_ITM_ITM_BOM_Recipe RecipeId
        {
            get { return _RecipeId; }
            set { SetPropertyValue<CDS_ITM_ITM_BOM_Recipe>("RecipeId", ref _RecipeId, value); }
        }
        CDS_SYS_SYS_Entity _ItemId;
        [Association(@"CDS_ITM_ITM_BOM_RecipeLineReferencesCDS_SYS_SYS_Entity")]
        public CDS_SYS_SYS_Entity ItemId
        {
            get { return _ItemId; }
            set { SetPropertyValue<CDS_SYS_SYS_Entity>("ItemId", ref _ItemId, value); }
        }
        decimal _Quantity;
        public decimal Quantity
        {
            get { return _Quantity; }
            set { SetPropertyValue<decimal>("Quantity", ref _Quantity, value); }
        }
        decimal _Amount;
        public decimal Amount
        {
            get { return _Amount; }
            set { SetPropertyValue<decimal>("Amount", ref _Amount, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        CDS_SYS_SYS_Person _CreatedBy;
        [Association(@"CDS_ITM_ITM_BOM_RecipeLineReferencesCDS_SYS_SYS_Person")]
        public CDS_SYS_SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<CDS_SYS_SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
    }

}
