//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class GLX_Type : XPLiteObject
    {
        byte _Id;
        [Key]
        public byte Id
        {
            get { return _Id; }
            set { SetPropertyValue<byte>("Id", ref _Id, value); }
        }
        string _Grouping;
        [Size(50)]
        public string Grouping
        {
            get { return _Grouping; }
            set { SetPropertyValue<string>("Grouping", ref _Grouping, value); }
        }
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _Description;
        [Size(2000)]
        public string Description
        {
            get { return _Description; }
            set { SetPropertyValue<string>("Description", ref _Description, value); }
        }
        char _Flag1;
        public char Flag1
        {
            get { return _Flag1; }
            set { SetPropertyValue<char>("Flag1", ref _Flag1, value); }
        }
        string _Flag2;
        [Size(2)]
        public string Flag2
        {
            get { return _Flag2; }
            set { SetPropertyValue<string>("Flag2", ref _Flag2, value); }
        }
        [Association(@"GLX_AccountReferencesGLX_Type", typeof(GLX_Account))]
        public XPCollection<GLX_Account> GLX_Accounts { get { return GetCollection<GLX_Account>("GLX_Accounts"); } }
        [Association(@"GLX_SystemAccountTypeReferencesGLX_Type", typeof(GLX_SystemAccountType))]
        public XPCollection<GLX_SystemAccountType> GLX_SystemAccountTypes { get { return GetCollection<GLX_SystemAccountType>("GLX_SystemAccountTypes"); } }
    }

}
