//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class HRS_Role : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        string _Code;
        [Size(50)]
        public string Code
        {
            get { return _Code; }
            set { SetPropertyValue<string>("Code", ref _Code, value); }
        }
        string _Name;
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        string _Description;
        [Size(2000)]
        public string Description
        {
            get { return _Description; }
            set { SetPropertyValue<string>("Description", ref _Description, value); }
        }
        bool _Appointment;
        public bool Appointment
        {
            get { return _Appointment; }
            set { SetPropertyValue<bool>("Appointment", ref _Appointment, value); }
        }
        bool _SaleAppointment;
        public bool SaleAppointment
        {
            get { return _SaleAppointment; }
            set { SetPropertyValue<bool>("SaleAppointment", ref _SaleAppointment, value); }
        }
        bool _PurchaseAppointment;
        public bool PurchaseAppointment
        {
            get { return _PurchaseAppointment; }
            set { SetPropertyValue<bool>("PurchaseAppointment", ref _PurchaseAppointment, value); }
        }
        bool _WorkshopAppointment;
        public bool WorkshopAppointment
        {
            get { return _WorkshopAppointment; }
            set { SetPropertyValue<bool>("WorkshopAppointment", ref _WorkshopAppointment, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        SYS_Person _CreatedBy;
        [Association(@"HRS_RoleReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
        [Association(@"HRS_EmployeeReferencesHRS_Role", typeof(HRS_Employee))]
        public XPCollection<HRS_Employee> HRS_Employees { get { return GetCollection<HRS_Employee>("HRS_Employees"); } }
    }

}
