//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class ORG_Company : XPLiteObject
    {
        long _Id;
        [Key(true)]
        public long Id
        {
            get { return _Id; }
            set { SetPropertyValue<long>("Id", ref _Id, value); }
        }
        ORG_Entity _EntityId;
        [Association(@"ORG_CompanyReferencesORG_Entity")]
        public ORG_Entity EntityId
        {
            get { return _EntityId; }
            set { SetPropertyValue<ORG_Entity>("EntityId", ref _EntityId, value); }
        }
        ORG_Type _TypeId;
        [Association(@"ORG_CompanyReferencesORG_Type")]
        public ORG_Type TypeId
        {
            get { return _TypeId; }
            set { SetPropertyValue<ORG_Type>("TypeId", ref _TypeId, value); }
        }
        ORG_PaymentTerm _PaymentTermId;
        [Association(@"ORG_CompanyReferencesORG_PaymentTerm")]
        public ORG_PaymentTerm PaymentTermId
        {
            get { return _PaymentTermId; }
            set { SetPropertyValue<ORG_PaymentTerm>("PaymentTermId", ref _PaymentTermId, value); }
        }
        ORG_CostCategory _CostCategoryId;
        [Association(@"ORG_CompanyReferencesORG_CostCategory")]
        public ORG_CostCategory CostCategoryId
        {
            get { return _CostCategoryId; }
            set { SetPropertyValue<ORG_CostCategory>("CostCategoryId", ref _CostCategoryId, value); }
        }
        SYS_Entity _AccountId;
        [Association(@"ORG_CompanyReferencesSYS_Entity")]
        public SYS_Entity AccountId
        {
            get { return _AccountId; }
            set { SetPropertyValue<SYS_Entity>("AccountId", ref _AccountId, value); }
        }
        string _Prefix;
        [Size(50)]
        public string Prefix
        {
            get { return _Prefix; }
            set { SetPropertyValue<string>("Prefix", ref _Prefix, value); }
        }
        bool _OpenItem;
        public bool OpenItem
        {
            get { return _OpenItem; }
            set { SetPropertyValue<bool>("OpenItem", ref _OpenItem, value); }
        }
        bool _Active;
        public bool Active
        {
            get { return _Active; }
            set { SetPropertyValue<bool>("Active", ref _Active, value); }
        }
        bool _OverrideAccount;
        public bool OverrideAccount
        {
            get { return _OverrideAccount; }
            set { SetPropertyValue<bool>("OverrideAccount", ref _OverrideAccount, value); }
        }
        decimal _AccountLimit;
        public decimal AccountLimit
        {
            get { return _AccountLimit; }
            set { SetPropertyValue<decimal>("AccountLimit", ref _AccountLimit, value); }
        }
        string _DiscountCode;
        [Size(20)]
        public string DiscountCode
        {
            get { return _DiscountCode; }
            set { SetPropertyValue<string>("DiscountCode", ref _DiscountCode, value); }
        }
        string _TagCode;
        [Size(20)]
        public string TagCode
        {
            get { return _TagCode; }
            set { SetPropertyValue<string>("TagCode", ref _TagCode, value); }
        }
        string _AreaCode;
        [Size(20)]
        public string AreaCode
        {
            get { return _AreaCode; }
            set { SetPropertyValue<string>("AreaCode", ref _AreaCode, value); }
        }
        string _RepCode;
        [Size(20)]
        public string RepCode
        {
            get { return _RepCode; }
            set { SetPropertyValue<string>("RepCode", ref _RepCode, value); }
        }
        string _SalesmanCode;
        [Size(20)]
        public string SalesmanCode
        {
            get { return _SalesmanCode; }
            set { SetPropertyValue<string>("SalesmanCode", ref _SalesmanCode, value); }
        }
        string _StatementPreference;
        [Size(20)]
        public string StatementPreference
        {
            get { return _StatementPreference; }
            set { SetPropertyValue<string>("StatementPreference", ref _StatementPreference, value); }
        }
        string _CountryCode;
        [Size(20)]
        public string CountryCode
        {
            get { return _CountryCode; }
            set { SetPropertyValue<string>("CountryCode", ref _CountryCode, value); }
        }
        string _URL;
        [Size(50)]
        public string URL
        {
            get { return _URL; }
            set { SetPropertyValue<string>("URL", ref _URL, value); }
        }
        string _Username;
        [Size(50)]
        public string Username
        {
            get { return _Username; }
            set { SetPropertyValue<string>("Username", ref _Username, value); }
        }
        string _Password;
        [Size(50)]
        public string Password
        {
            get { return _Password; }
            set { SetPropertyValue<string>("Password", ref _Password, value); }
        }
        string _CustomValue1;
        [Size(50)]
        public string CustomValue1
        {
            get { return _CustomValue1; }
            set { SetPropertyValue<string>("CustomValue1", ref _CustomValue1, value); }
        }
        string _CustomValue2;
        [Size(50)]
        public string CustomValue2
        {
            get { return _CustomValue2; }
            set { SetPropertyValue<string>("CustomValue2", ref _CustomValue2, value); }
        }
        string _CustomValue3;
        [Size(50)]
        public string CustomValue3
        {
            get { return _CustomValue3; }
            set { SetPropertyValue<string>("CustomValue3", ref _CustomValue3, value); }
        }
        string _CustomValue4;
        [Size(50)]
        public string CustomValue4
        {
            get { return _CustomValue4; }
            set { SetPropertyValue<string>("CustomValue4", ref _CustomValue4, value); }
        }
        string _CustomValue5;
        [Size(50)]
        public string CustomValue5
        {
            get { return _CustomValue5; }
            set { SetPropertyValue<string>("CustomValue5", ref _CustomValue5, value); }
        }
        string _CustomValue6;
        [Size(50)]
        public string CustomValue6
        {
            get { return _CustomValue6; }
            set { SetPropertyValue<string>("CustomValue6", ref _CustomValue6, value); }
        }
        DateTime _CreatedOn;
        public DateTime CreatedOn
        {
            get { return _CreatedOn; }
            set { SetPropertyValue<DateTime>("CreatedOn", ref _CreatedOn, value); }
        }
        SYS_Person _CreatedBy;
        [Association(@"ORG_CompanyReferencesSYS_Person")]
        public SYS_Person CreatedBy
        {
            get { return _CreatedBy; }
            set { SetPropertyValue<SYS_Person>("CreatedBy", ref _CreatedBy, value); }
        }
        SYS_Entity _SiteId;
        [Association(@"ORG_CompanyReferencesSYS_Entity1")]
        public SYS_Entity SiteId
        {
            get { return _SiteId; }
            set { SetPropertyValue<SYS_Entity>("SiteId", ref _SiteId, value); }
        }
        [Association(@"ORG_CompanyAddressReferencesORG_Company", typeof(ORG_CompanyAddress))]
        public XPCollection<ORG_CompanyAddress> ORG_CompanyAddresss { get { return GetCollection<ORG_CompanyAddress>("ORG_CompanyAddresss"); } }
        [Association(@"ORG_HistoryReferencesORG_Company", typeof(ORG_History))]
        public XPCollection<ORG_History> ORG_Historys { get { return GetCollection<ORG_History>("ORG_Historys"); } }
        [Association(@"ORG_TRX_HeaderReferencesORG_Company", typeof(ORG_TRX_Header))]
        public XPCollection<ORG_TRX_Header> ORG_TRX_Headers { get { return GetCollection<ORG_TRX_Header>("ORG_TRX_Headers"); } }
        [Association(@"ORG_TRX_LostSaleReferencesORG_Company", typeof(ORG_TRX_LostSale))]
        public XPCollection<ORG_TRX_LostSale> ORG_TRX_LostSales { get { return GetCollection<ORG_TRX_LostSale>("ORG_TRX_LostSales"); } }
        [Association(@"IBO_TRX_HeaderReferencesORG_Company", typeof(IBO_TRX_Header))]
        public XPCollection<IBO_TRX_Header> IBO_TRX_Headers { get { return GetCollection<IBO_TRX_Header>("IBO_TRX_Headers"); } }
        [Association(@"IBO_TRX_HeaderReferencesORG_Company1", typeof(IBO_TRX_Header))]
        public XPCollection<IBO_TRX_Header> IBO_TRX_Headers1 { get { return GetCollection<IBO_TRX_Header>("IBO_TRX_Headers1"); } }
        [Association(@"SYS_SiteReferencesORG_Company", typeof(SYS_Site))]
        public XPCollection<SYS_Site> SYS_Sites { get { return GetCollection<SYS_Site>("SYS_Sites"); } }
        [Association(@"JOB_HeaderReferencesORG_Company", typeof(JOB_Header))]
        public XPCollection<JOB_Header> JOB_Headers { get { return GetCollection<JOB_Header>("JOB_Headers"); } }
        [Association(@"ORG_DistributionReferencesORG_Company", typeof(ORG_Distribution))]
        public XPCollection<ORG_Distribution> ORG_Distributions { get { return GetCollection<ORG_Distribution>("ORG_Distributions"); } }
    }

}
