//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CDS.Client.DataAccessLayer.XDB
{

    public partial class SYS_Type : XPLiteObject
    {
        byte _Id;
        [Key]
        public byte Id
        {
            get { return _Id; }
            set { SetPropertyValue<byte>("Id", ref _Id, value); }
        }
        string _Name;
        [Size(20)]
        public string Name
        {
            get { return _Name; }
            set { SetPropertyValue<string>("Name", ref _Name, value); }
        }
        [Association(@"SYS_AddressReferencesSYS_Type", typeof(SYS_Address))]
        public XPCollection<SYS_Address> SYS_Addresss { get { return GetCollection<SYS_Address>("SYS_Addresss"); } }
        [Association(@"SYS_EntityReferencesSYS_Type", typeof(SYS_Entity))]
        public XPCollection<SYS_Entity> SYS_Entitys { get { return GetCollection<SYS_Entity>("SYS_Entitys"); } }
    }

}
