DECLARE @EntityId BIGINT
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00001','00000','BANK','BANK','',0,1,GETDATE())													SET @EntityId = SCOPE_IDENTITY();	INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,1,1,'BANK',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00002','00000','CDS CARD CONTROL','CDS CARD CONTROL','',0,1,GETDATE())                          SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,2,1,'CARD CONTROL',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00003','00000','CDS CASH CONTROL','CDS CASH CONTROL','',0,1,GETDATE())                          SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,3,1,'CASH CONTROL',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00004','00000','CDS CHEQUE CONTROL','CDS CHEQUE CONTROL','',0,1,GETDATE())                      SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,4,1,'CHEQUE CONTROL',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00005','00000','PURCHASE COST DIFFERENCE','PURCHASE COST DIFFERENCE','',0,1,GETDATE())          SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,2,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,5,1,'COST DIFFERENCE',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00006','00000','COST OF SALES','COST OF SALES','',0,1,GETDATE())                                SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,2,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,6,1,'COST OF SALES',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00007','00000','CDS CREDIT CONTROL','CDS CREDIT CONTROL','',0,1,GETDATE())                      SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,7,1,'CREDIT CONTROL',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00008','00000','CREDITORS','CREDITORS','',0,1,GETDATE())                                        SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,5,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,8,1,'CREDITORS',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00009','00000','DEBTORS','DEBTORS','',0,1,GETDATE())                                            SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,9,1,'DEBTORS',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00010','00000','CDS DISTRIBUTED RESERVES','CDS DISTRIBUTED RESERVES','',0,1,GETDATE())          SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,6,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,10,1,'DISTRIBUTEDRESERVES',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00011','00000','CDS EFT CONTROL','CDS EFT CONTROL','',0,1,GETDATE())                            SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,11,1,'EFT CONTROL',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00012','00000','INTEREST CHARGED','INTEREST CHARGED','',0,1,GETDATE())                          SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,12,1,'INTEREST CHARGED',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00013','00000','INVENTORY','INVENTORY','',0,1,GETDATE())                                        SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,13,1,'INVENTORY',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00015','00000','CDS PROFIT','CDS PROFIT','',0,1,GETDATE())                                      SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,6,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,14,1,'PROFIT',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00016','00000','ROUNDING EXPENCES','ROUNDING EXPENCES','',0,1,GETDATE())                        SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,2,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,16,1,'ROUNDING',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00017','00000','SALES','SALES','',0,1,GETDATE())                                                SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,1,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,17,1,'SALES',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00018','00000','SETTLEMENT DISCOUNT ALLOWED','SETTLEMENT DISCOUNT ALLOWED','',0,1,GETDATE())    SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,3,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,18,1,'SET\D ALLOWED',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00019','00000','SETTLEMENT DISCOUNT RECEIVED','SETTLEMENT DISCOUNT RECEIVED','',0,1,GETDATE())  SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,3,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,19,1,'SET\D RECEIVED',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00020','00000','STOCK ADJUSTMENT','STOCK ADJUSTMENT','',0,1,GETDATE())                          SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,2,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,20,1,'STOCK ADJUSTMENT',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00021','00000','VAT ACCOUNT','VAT ACCOUNT','',0,1,GETDATE())                                    SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,7,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,21,1,'VAT CONTROL',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00022','00000','VAT INPUT','VAT INPUT','',0,1,GETDATE())                                        SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,22,1,'VAT INPUT',GETDATE(),1) 
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00023','00000','VAT OUTPUT','VAT OUTPUT','',0,1,GETDATE())                                      SET @EntityId = SCOPE_IDENTITY();   INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,5,NULL,0,GETDATE(),1,NULL,NULL,'')	INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,23,1,'VAT OUTPUT',GETDATE(),1) 

--Setup Buyout Account
INSERT INTO [CDS_SYS].[SYS_Entity] (TypeId,CodeMain,CodeSub,ShortName,Name,Description,Archived,CreatedBy,CreatedOn) VALUES (5,'00013','00001','INVENTORY BUYOUT','INVENTORY BUYOUT','',0,1,GETDATE())                          
SET @EntityId = SCOPE_IDENTITY();   
DECLARE @AccountId BIGINT;
SELECT @AccountId = Id from [CDS_SYS].[SYS_Entity] WHERE ShortName = 'INVENTORY';
INSERT INTO [CDS_GLX].[GLX_Account] (EntityId,AccountTypeId,CenterId,AgingAccount,CreatedOn,CreatedBy,ControlId,MasterControlId,BalanceGroup) VALUES (@EntityId,4,NULL,0,GETDATE(),1,@EntityId,@AccountId,'')	
INSERT INTO [CDS_GLX].[GLX_SiteAccount] (EntityId,TypeId,SystemDefaultAccount,ShortDescription,CreatedOn,CreatedBy) VALUES (@EntityId,24,1,'INVENTORY BUYOUT',GETDATE(),1) 