//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    
    public partial class GLX_Recon : INotifyPropertyChanged, IBaseEntity
    { 
    	bool hasChanges = false;
        public bool HasChanges
        {
        	get
        	{
                return hasChanges;
        	}
        	set
        	{
                if (hasChanges != value)
                    hasChanges = value;
        	}
        } 
    	
    	bool ignoreChanges = false;
        public bool IgnoreChanges
        {
            get
            {
                
                
                return ignoreChanges;
            }
            set
            {
                if (ignoreChanges != value)
                {
                    ignoreChanges = value;
                }
            }
        }
    
    	List<string> changeList = new List<string>();
    	[Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
        public List<string> ChangeList
        {
            get
            { 
                return changeList;
            }
            set
            {
                if (changeList != value)
                {
                    changeList = value;
                }
            }
        } 
    
    	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged; 
    	private void SetProperty<T>(ref T field, T value, [System.Runtime.CompilerServices.CallerMemberName] string name = "")
    	{
    		if (!EqualityComparer<T>.Default.Equals(field, value))
    		{
    			field = value;
    			//ChangeSet.Add(LogEntry.New<T>(field.ToString(),this.ToString(), this.Id,  field,  value ));
    			var handler = PropertyChanged;
    			if (handler != null)
    			{
    				if(!name.StartsWith("Id") && name != "Title" && name != "CreatedOn" && !IgnoreChanges)  
    				{
    					HasChanges = true;
    					ChangeList.Add(name);
    				}
    
    				handler(this, new System.ComponentModel.PropertyChangedEventArgs(name));
    			}
    		}
    	} 
     
        public GLX_Recon()
        {
            this.GLX_Line = new List<GLX_Line>();
        }
    
        private long id;
        private string reference;
        private string description;
        private Nullable<System.DateTime> startDate;
        private Nullable<System.DateTime> endDate;
        private Nullable<decimal> startAmount;
        private Nullable<decimal> endAmount;
        private Nullable<byte> statusId;
        private Nullable<long> createdBy;
        private Nullable<System.DateTime> createdOn;
        private string title;
    
        public long Id 
    	{ 
    		get { return id; }
    		set { SetProperty(ref id, value); }
    	 }
        public string Reference 
    	{ 
    		get { return reference; }
    		set { SetProperty(ref reference, value); }
    	 }
        public string Description 
    	{ 
    		get { return description; }
    		set { SetProperty(ref description, value); }
    	 }
        public Nullable<System.DateTime> StartDate 
    	{ 
    		get { return startDate; }
    		set { SetProperty(ref startDate, value); }
    	 }
        public Nullable<System.DateTime> EndDate 
    	{ 
    		get { return endDate; }
    		set { SetProperty(ref endDate, value); }
    	 }
        public Nullable<decimal> StartAmount 
    	{ 
    		get { return startAmount; }
    		set { SetProperty(ref startAmount, value); }
    	 }
        public Nullable<decimal> EndAmount 
    	{ 
    		get { return endAmount; }
    		set { SetProperty(ref endAmount, value); }
    	 }
        public Nullable<byte> StatusId 
    	{ 
    		get { return statusId; }
    		set { SetProperty(ref statusId, value); }
    	 }
        public Nullable<long> CreatedBy 
    	{ 
    		get { return createdBy; }
    		set { SetProperty(ref createdBy, value); }
    	 }
        public Nullable<System.DateTime> CreatedOn 
    	{ 
    		get { return createdOn; }
    		set { SetProperty(ref createdOn, value); }
    	 }
        public string Title 
    	{ 
    		get { return title; }
    		set { SetProperty(ref title, value); }
    	 }
    
        [System.Xml.Serialization.XmlIgnore]
    	public virtual ICollection<GLX_Line> GLX_Line { get; set; }
    }
}
