//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    
    public partial class SYS_Version : INotifyPropertyChanged, IBaseEntity
    { 
    	bool hasChanges = false;
        public bool HasChanges
        {
        	get
        	{
                return hasChanges;
        	}
        	set
        	{
                if (hasChanges != value)
                    hasChanges = value;
        	}
        } 
    	
    	bool ignoreChanges = false;
        public bool IgnoreChanges
        {
            get
            {
                
                
                return ignoreChanges;
            }
            set
            {
                if (ignoreChanges != value)
                {
                    ignoreChanges = value;
                }
            }
        }
    
    	List<string> changeList = new List<string>();
    	[Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
        public List<string> ChangeList
        {
            get
            { 
                return changeList;
            }
            set
            {
                if (changeList != value)
                {
                    changeList = value;
                }
            }
        } 
    
    	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged; 
    	private void SetProperty<T>(ref T field, T value, [System.Runtime.CompilerServices.CallerMemberName] string name = "")
    	{
    		if (!EqualityComparer<T>.Default.Equals(field, value))
    		{
    			field = value;
    			//ChangeSet.Add(LogEntry.New<T>(field.ToString(),this.ToString(), this.Id,  field,  value ));
    			var handler = PropertyChanged;
    			if (handler != null)
    			{
    				if(!name.StartsWith("Id") && name != "Title" && name != "CreatedOn" && !IgnoreChanges)  
    				{
    					HasChanges = true;
    					ChangeList.Add(name);
    				}
    
    				handler(this, new System.ComponentModel.PropertyChangedEventArgs(name));
    			}
    		}
    	} 
     
        private long id;
        private string version;
        private string description;
        private byte[] clientDirector;
        private byte[] clientUpdate;
        private string versionPadded;
        private byte[] webDirector;
        private byte[] webUpdate;
        private Nullable<System.DateTime> createdOn;
        private Nullable<long> createdBy;
        private Nullable<System.DateTime> modifiedOn;
        private string modifiedBy;
    
        public long Id 
    	{ 
    		get { return id; }
    		set { SetProperty(ref id, value); }
    	 }
        public string Version 
    	{ 
    		get { return version; }
    		set { SetProperty(ref version, value); }
    	 }
        public string Description 
    	{ 
    		get { return description; }
    		set { SetProperty(ref description, value); }
    	 }
        public byte[] ClientDirector 
    	{ 
    		get { return clientDirector; }
    		set { SetProperty(ref clientDirector, value); }
    	 }
        public byte[] ClientUpdate 
    	{ 
    		get { return clientUpdate; }
    		set { SetProperty(ref clientUpdate, value); }
    	 }
        public string VersionPadded 
    	{ 
    		get { return versionPadded; }
    		set { SetProperty(ref versionPadded, value); }
    	 }
        public byte[] WebDirector 
    	{ 
    		get { return webDirector; }
    		set { SetProperty(ref webDirector, value); }
    	 }
        public byte[] WebUpdate 
    	{ 
    		get { return webUpdate; }
    		set { SetProperty(ref webUpdate, value); }
    	 }
        public Nullable<System.DateTime> CreatedOn 
    	{ 
    		get { return createdOn; }
    		set { SetProperty(ref createdOn, value); }
    	 }
        public Nullable<long> CreatedBy 
    	{ 
    		get { return createdBy; }
    		set { SetProperty(ref createdBy, value); }
    	 }
        public Nullable<System.DateTime> ModifiedOn 
    	{ 
    		get { return modifiedOn; }
    		set { SetProperty(ref modifiedOn, value); }
    	 }
        public string ModifiedBy 
    	{ 
    		get { return modifiedBy; }
    		set { SetProperty(ref modifiedBy, value); }
    	 }
    
        
    	public virtual SYS_Person SYS_Person { get; set; }
    }
}
