//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Alternative
    {
        public long Id { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string SearchItemName { get; set; }
        public string AlternativeItemName { get; set; }
        public string ShortName { get; set; }
        public decimal OnHand { get; set; }
    }
}
