//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Budget
    {
        public Nullable<long> Id { get; set; }
        public string EntryType { get; set; }
        public long AccountId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime PeriodStartDate { get; set; }
        public System.DateTime PeriodEndDate { get; set; }
        public string PeriodCode { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public string StatusCode { get; set; }
        public string TypeCode { get; set; }
        public Nullable<short> FinancialYear { get; set; }
    }
}
