//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Employee
    {
        public long Id { get; set; }
        public long RoleId { get; set; }
        public string Code { get; set; }
        public string Salutation { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Nickname { get; set; }
        public string Fullname { get; set; }
        public string IdNumber { get; set; }
        public string RoleName { get; set; }
    }
}
