//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Header
    {
        public long Id { get; set; }
        public Nullable<byte> JournalTypeId { get; set; }
        public string JournalType { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> HeaderDay { get; set; }
        public long TrackId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string StatusCode { get; set; }
        public string PeriodCode { get; set; }
        public Nullable<long> ReferenceId { get; set; }
    }
}
