//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDS.Client.DataAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Job
    {
        public long Id { get; set; }
        public Nullable<long> DocumentNumber { get; set; }
        public string ReferenceShort1 { get; set; }
        public string ReferenceShort2 { get; set; }
        public string ReferenceShort3 { get; set; }
        public string ReferenceShort4 { get; set; }
        public string ReferenceShort5 { get; set; }
        public string ReferenceShort6 { get; set; }
        public string ReferenceShort7 { get; set; }
        public string ReferenceShort8 { get; set; }
        public string ReferenceShort9 { get; set; }
        public string ReferenceShort10 { get; set; }
        public string ReferenceLong1 { get; set; }
        public string ReferenceLong2 { get; set; }
        public string ReferenceLong3 { get; set; }
        public string ReferenceLong4 { get; set; }
        public string ReferenceLong5 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public string Telephone { get; set; }
        public string ContactPerson { get; set; }
        public string ContactTelephone { get; set; }
        public long TrackingNumber { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> TotalExcl { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Lines { get; set; }
    }
}
